#ivy cached data file for net.sourceforge.cssparser#cssparser;0.9.16
#Wed Jun 22 11:43:53 PDT 2016
artifact\:cssparser\#jar\#jar\#-343324394.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/sourceforge/cssparser/cssparser/0.9.16/cssparser-0.9.16.jar
artifact\:ivy\#ivy\#xml\#-551687367.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/sourceforge/cssparser/cssparser/0.9.16/cssparser-0.9.16.pom
artifact.resolver=maven
artifact\:cssparser\#jar\#jar\#-343324394.is-local=false
artifact\:cssparser\#pom.original\#pom\#1309238268.is-local=false
artifact\:cssparser\#pom.original\#pom\#1309238268.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/sourceforge/cssparser/cssparser/0.9.16/cssparser-0.9.16.pom
artifact\:ivy\#ivy\#xml\#-551687367.is-local=false
resolver=maven
