#ivy cached data file for org.seleniumhq.selenium#selenium-parent;2.47.1
#Wed Jun 22 11:42:39 PDT 2016
artifact\:ivy\#ivy\#xml\#-1064530039.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-parent/2.47.1/selenium-parent-2.47.1.pom
artifact\:ivy\#ivy\#xml\#-1064530039.is-local=false
artifact.resolver=maven
artifact\:selenium-parent\#pom.original\#pom\#1649509707.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-parent/2.47.1/selenium-parent-2.47.1.pom
artifact\:selenium-parent\#pom.original\#pom\#1649509707.is-local=false
resolver=maven
