#ivy cached data file for org.seleniumhq.selenium#selenium-parent;2.53.0
#Fri Sep 16 11:26:12 PDT 2016
artifact\:selenium-parent\#pom.original\#pom\#1811750045.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-parent/2.53.0/selenium-parent-2.53.0.pom
artifact\:selenium-parent\#pom.original\#pom\#1811750045.is-local=false
artifact\:ivy\#ivy\#xml\#-902289701.is-local=false
artifact\:ivy\#ivy\#xml\#-902289701.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-parent/2.53.0/selenium-parent-2.53.0.pom
artifact.resolver=maven
resolver=maven
