#ivy cached data file for com.github.scribejava#scribejava-core;3.2.0
#Thu Jan 05 15:28:37 PST 2017
artifact\:scribejava-core\#jar\#jar\#480777699.is-local=false
artifact\:scribejava-core\#pom.original\#pom\#2133340361.location=https\://plugins.gradle.org/m2/com/github/scribejava/scribejava-core/3.2.0/scribejava-core-3.2.0.pom
artifact.resolver=maven
artifact\:scribejava-core\#pom.original\#pom\#2133340361.is-local=false
artifact\:ivy\#ivy\#xml\#-1137195016.location=https\://plugins.gradle.org/m2/com/github/scribejava/scribejava-core/3.2.0/scribejava-core-3.2.0.pom
artifact\:ivy\#ivy\#xml\#-1137195016.is-local=false
artifact\:scribejava-core\#jar\#jar\#480777699.location=https\://plugins.gradle.org/m2/com/github/scribejava/scribejava-core/3.2.0/scribejava-core-3.2.0.jar
resolver=maven
