##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Sapphire'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Sapphire')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Sapphire')

##
## Poshi
##

    portal.url=http://<project-uat-url>

    save.screenshot=false

    test.base.dir.name=testFunctional/
    
    test.case.available.property.names=\
        testray.main.component.name

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.sapphire.portal.url.uat=https://emu.sapphiregroup.com.au/
    test.this.sapphire.portal.url.prod=https://sos.sapphiregroup.com.au/

    test.this.sapphire.test.account.uat.user.login=lfrgs-sapphire-commerce@gs.liferay.com
    test.this.sapphire.test.account.uat.user.password=7if3ray@5apphir3

##
## Testray
##

    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.project.name=LXC

    testray.routine.name[uat]=MODL Daily