environmentBrowserName=Google Chrome 100
environmentOperatingSystemName=Ubuntu 22.04.1
projectDir=.
testrayBuildName=sapphiregroup.com.au - $(start.time)
testrayCasePriority=1
testrayComponentName=Sapphire
testrayProductVersion=1.x
testrayProjectName=LXC
testrayRoutineName=MODL Daily
testrayServerURL=https://testray.liferay.com
testrayTeamName=Sapphire