environmentBrowserName=Google Chrome 86
environmentOperatingSystemName=CentOS 7
projectDir=.
testrayBuildName=ci:test:uat - $(start.time)
testrayCasePriority=1
testrayComponentName=Sapphire
testrayProductVersion=1.x
testrayProjectName=LXC
testrayRoutineName=MODL Daily
testrayServerURL=https://testray.liferay.com
testrayTeamName=
testrayUserName=[liferay_user_name]@liferay.com
testrayUserPassword=[liferay_user_password]