#ivy cached data file for org.apache.httpcomponents#httpcomponents-client;4.5.1
#Fri Sep 16 11:26:32 PDT 2016
artifact\:httpcomponents-client\#pom.original\#pom\#-132970772.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-client/4.5.1/httpcomponents-client-4.5.1.pom
artifact.resolver=maven
artifact\:httpcomponents-client\#pom.original\#pom\#-132970772.is-local=false
artifact\:ivy\#ivy\#xml\#-422080015.is-local=false
artifact\:ivy\#ivy\#xml\#-422080015.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-client/4.5.1/httpcomponents-client-4.5.1.pom
resolver=maven
