#ivy cached data file for org.apache.httpcomponents#httpcomponents-client;4.5.2
#Thu Sep 21 18:55:17 PDT 2017
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-422073762.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpcomponents-client/4.5.2/httpcomponents-client-4.5.2.pom
artifact\:ivy\#ivy\#xml\#-422073762.is-local=false
artifact\:httpcomponents-client\#pom.original\#pom\#-132964519.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpcomponents-client/4.5.2/httpcomponents-client-4.5.2.pom
resolver=maven
artifact\:httpcomponents-client\#pom.original\#pom\#-132964519.is-local=false
