#ivy cached data file for org.apache.httpcomponents#httpcomponents-client;4.3.3
#Fri Sep 16 11:25:46 PDT 2016
artifact.resolver=maven
artifact\:httpcomponents-client\#pom.original\#pom\#-144976532.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-client/4.3.3/httpcomponents-client-4.3.3.pom
artifact\:httpcomponents-client\#pom.original\#pom\#-144976532.is-local=false
artifact\:ivy\#ivy\#xml\#-434085775.is-local=false
artifact\:ivy\#ivy\#xml\#-434085775.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-client/4.3.3/httpcomponents-client-4.3.3.pom
resolver=maven
