#ivy cached data file for org.bytedeco.javacpp-presets#opencv;2.4.9-0.9
#Fri Sep 16 11:55:14 PDT 2016
artifact\:opencv\#jar\#jar\#-1563474416.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/bytedeco/javacpp-presets/opencv/2.4.9-0.9/opencv-2.4.9-0.9.jar
artifact\:opencv\#pom.original\#pom\#89088246.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/bytedeco/javacpp-presets/opencv/2.4.9-0.9/opencv-2.4.9-0.9.pom
artifact\:opencv\#javadoc\#jar\#-1214927605.is-local=false
resolver=maven
artifact\:opencv\#jar\#jar\#-1563474416.is-local=false
artifact\:opencv\#pom.original\#pom\#89088246.is-local=false
artifact\:ivy\#ivy\#xml\#-916854384.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/bytedeco/javacpp-presets/opencv/2.4.9-0.9/opencv-2.4.9-0.9.pom
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-916854384.is-local=false
artifact\:opencv\#source\#jar\#80084894.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/bytedeco/javacpp-presets/opencv/2.4.9-0.9/opencv-2.4.9-0.9-sources.jar
artifact\:opencv\#javadoc\#jar\#-1214927605.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/bytedeco/javacpp-presets/opencv/2.4.9-0.9/opencv-2.4.9-0.9-javadoc.jar
artifact\:opencv\#source\#jar\#80084894.is-local=false
