#ivy cached data file for org.bytedeco.javacpp-presets#opencv;2.4.10-0.10
#Wed Oct 19 10:24:42 PDT 2016
artifact\:opencv\#pom.original\#pom\#1164223690.is-local=false
artifact\:opencv\#pom.original\#pom\#1164223690.location=https\://plugins.gradle.org/m2/org/bytedeco/javacpp-presets/opencv/2.4.10-0.10/opencv-2.4.10-0.10.pom
artifact\:opencv\#javadoc\#jar\#-139792161.is-local=false
resolver=maven
artifact\:opencv\#javadoc\#jar\#-139792161.location=https\://plugins.gradle.org/m2/org/bytedeco/javacpp-presets/opencv/2.4.10-0.10/opencv-2.4.10-0.10-javadoc.jar
artifact\:opencv\#jar\#jar\#-488338972.is-local=false
artifact\:opencv\#jar\#jar\#-488338972.location=https\://plugins.gradle.org/m2/org/bytedeco/javacpp-presets/opencv/2.4.10-0.10/opencv-2.4.10-0.10.jar
artifact\:ivy\#ivy\#xml\#158281060.is-local=false
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#158281060.location=https\://plugins.gradle.org/m2/org/bytedeco/javacpp-presets/opencv/2.4.10-0.10/opencv-2.4.10-0.10.pom
artifact\:opencv\#source\#jar\#1155220338.is-local=false
artifact\:opencv\#source\#jar\#1155220338.location=https\://plugins.gradle.org/m2/org/bytedeco/javacpp-presets/opencv/2.4.10-0.10/opencv-2.4.10-0.10-sources.jar
