#ivy cached data file for commons-lang#commons-lang;2.6
#Wed Oct 19 10:24:42 PDT 2016
artifact\:commons-lang\#jar\#jar\#538655611.is-local=false
artifact.resolver=maven
artifact\:commons-lang\#pom.original\#pom\#-2103749023.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/commons-lang/commons-lang/2.6/commons-lang-2.6.pom
artifact\:commons-lang\#pom.original\#pom\#-2103749023.is-local=false
artifact\:ivy\#ivy\#xml\#1530241013.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/commons-lang/commons-lang/2.6/commons-lang-2.6.pom
artifact\:commons-lang\#jar\#jar\#538655611.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
resolver=maven
artifact\:ivy\#ivy\#xml\#1530241013.is-local=false
