#ivy cached data file for org.apache.ant#ant-launcher;1.9.4
#Fri Sep 16 11:55:13 PDT 2016
artifact\:ant-launcher\#pom.original\#pom\#1169898894.is-local=false
artifact\:ant-launcher\#pom.original\#pom\#1169898894.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.pom
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#1567819143.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.pom
artifact\:ivy\#ivy\#xml\#1567819143.is-local=false
resolver=maven
artifact\:ant-launcher\#jar\#jar\#-482663768.is-local=false
artifact\:ant-launcher\#jar\#jar\#-482663768.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.jar
