#ivy cached data file for de.undercouch#gradle-download-task;3.2.0
#Thu Sep 21 18:55:20 PDT 2017
artifact\:gradle-download-task\#pom.original\#pom\#-1624780681.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.2.0/gradle-download-task-3.2.0.pom
artifact\:gradle-download-task\#javadoc\#jar\#1366170764.is-local=false
artifact\:gradle-download-task\#javadoc\#jar\#1366170764.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.2.0/gradle-download-task-3.2.0-javadoc.jar
artifact\:ivy\#ivy\#xml\#1714500162.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.2.0/gradle-download-task-3.2.0.pom
resolver=maven
artifact\:ivy\#ivy\#xml\#1714500162.is-local=false
artifact\:gradle-download-task\#jar\#jar\#1017623953.is-local=false
artifact\:gradle-download-task\#jar\#jar\#1017623953.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.2.0/gradle-download-task-3.2.0.jar
artifact\:gradle-download-task\#source\#jar\#-1633784033.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.2.0/gradle-download-task-3.2.0-sources.jar
artifact.resolver=maven
artifact\:gradle-download-task\#source\#jar\#-1633784033.is-local=false
artifact\:gradle-download-task\#pom.original\#pom\#-1624780681.is-local=false
