#ivy cached data file for net.saliman#gradle-properties-plugin;1.4.6
#Thu Sep 21 18:55:21 PDT 2017
artifact\:gradle-properties-plugin\#pom.original\#pom\#453104036.is-local=false
artifact\:gradle-properties-plugin\#javadoc\#jar\#-850911815.is-local=false
resolver=maven
artifact\:gradle-properties-plugin\#source\#jar\#444100684.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/saliman/gradle-properties-plugin/1.4.6/gradle-properties-plugin-1.4.6-sources.jar
artifact\:ivy\#ivy\#xml\#-1303702012.is-local=false
artifact\:gradle-properties-plugin\#source\#jar\#444100684.is-local=false
artifact\:ivy\#ivy\#xml\#-1303702012.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/saliman/gradle-properties-plugin/1.4.6/gradle-properties-plugin-1.4.6.pom
artifact\:gradle-properties-plugin\#jar\#jar\#-1199458626.is-local=false
artifact.resolver=maven
artifact\:gradle-properties-plugin\#jar\#jar\#-1199458626.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/saliman/gradle-properties-plugin/1.4.6/gradle-properties-plugin-1.4.6.jar
artifact\:gradle-properties-plugin\#pom.original\#pom\#453104036.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/saliman/gradle-properties-plugin/1.4.6/gradle-properties-plugin-1.4.6.pom
artifact\:gradle-properties-plugin\#javadoc\#jar\#-850911815.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/saliman/gradle-properties-plugin/1.4.6/gradle-properties-plugin-1.4.6-javadoc.jar
