import com.liferay.gradle.util.FileUtil
import com.liferay.gradle.util.StringUtil

import java.nio.file.Files

import java.util.regex.Matcher

import org.gradle.util.GUtil


apply plugin: "com.liferay.base.plugin"

task downloadBundle

task printLR() {
	doLast {
		println liferay.appServers.tomcat.binDir
	}
}

buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "latest.release"
    }

	repositories {
		mavenLocal()

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}

        maven {
			url "https://plugins.gradle.org/m2/"
		}

        maven {
			url file("/opt/dev/projects/github/liferay-portal/.m2-tmp")
		}
	}
}

 File f = project.file "../../../tmp/bundle/bundle.zip"
 File df = project.file "../../../tmp/dxp"
 def targetDir =  project.file "../../../tmp/dxp/liferay-dxp/tomcat/bin"

task unzipDxp(type: Copy) {
    dependsOn downloadBundle
    description = "Unzips the Liferay DXP bundle into the temporary folder."
    
    from zipTree(f)
    into df

    println liferay.appServers
}

task deleteDxp(type: Delete){
    delete f
    delete df
}

task runTomcat(type: Exec) {
    description = "Runs the Liferay DXP Tomcat server using ./catalina.sh run."

    dependsOn unzipDxp

    workingDir targetDir
    commandLine 'bash', '-c', './catalina.sh run' 

    standardInput = System.in
    standardOutput = System.out
    errorOutput = System.err
}

downloadBundle { 
    doLast {
        println "Hello foo"
		String url = "https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.42/bin/apache-tomcat-10.1.42.zip"
        println f.path
		FileUtil.get(project, url, f)

        println targetDir.path



        // exec {
        //     executable "bash"

        //     args "-c", "./catalina.sh run"

        //     workingDir targetDir
        // }
    }
}
