##
## Component Names
##

    component.names=support-qa

##
## Account Properties
##

    # Liferay employee
    kb.email.address.1=
    # customer
    kb.email.address.2=
    # partner
    kb.email.address.3=
    # trial user
    kb.email.address.4=
    # content creator
    kb.email.address.5=
    # kb admin
    kb.email.address.6=
    
    kb.email.password.1=test
    kb.email.password.2=test
    kb.email.password.3=test
    kb.email.password.4=test
    kb.email.password.5=test
    kb.email.password.6=test

##
## Testray
##

    testray.project.name=Support QA

##
## Test Batch
##

    test.batch.property.names=testray.main.component.name
    test.batch.property.values=Support QA

##
## Utilities
##

    customer.liferay.url=https://customer-upgrade.liferay.com
    test.base.dir.name=testFunctional
    
##
## Test Properties
##

    customer.liferay.url=https://customer-upgrade.liferay.com
