app.marketplace.id=15194315
app.marketplace.title=Liferay CE Social Bookmarks
<<<<<<< HEAD
app.marketplace.version=7.0.0
app.portal.build=7400
=======
app.marketplace.version=6.0.0
app.portal.build=7306
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
