#ivy cached data file for com.google.guava#guava-parent;19.0
#Fri Sep 16 11:26:26 PDT 2016
artifact\:guava-parent\#pom.original\#pom\#-54914215.is-local=false
artifact\:ivy\#ivy\#xml\#630518615.is-local=false
artifact\:ivy\#ivy\#xml\#630518615.location=https\://plugins.gradle.org/m2/com/google/guava/guava-parent/19.0/guava-parent-19.0.pom
artifact.resolver=maven
resolver=maven
artifact\:guava-parent\#pom.original\#pom\#-54914215.location=https\://plugins.gradle.org/m2/com/google/guava/guava-parent/19.0/guava-parent-19.0.pom
