##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Vale'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Vale')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Vale')

##
## Poshi
##

    portal.url=https://vale-uat.lxc.liferay.com

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        test.env,\
        testray.main.component.name

    test.name=HomePage,Menu

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.vale.portal.url.uat=https://vale-uat.lxc.liferay.com
    test.this.vale.portal.url.prod=http://<project-prod-url>

    test.this.vale.test.account.uat.admin.login=test@lxc.app
    test.this.vale.test.account.uat.admin.password=test

    test.this.vale.test.account.uat.user.login=<uat-user-login>
    test.this.vale.test.account.uat.user.password=<uat-user-password>

##
## Testray
##

    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.project.name=LXC

    testray.routine.name[uat]=MODL Daily