environmentBrowserName=Google Chrome 100
environmentOperatingSystemName=Ubuntu 22.04.1
projectDir=.
testrayBuildName=vale.com - $(start.time)
testrayCasePriority=1
testrayComponentName=Vale
testrayProductVersion=1.x
testrayProjectName=LXC
testrayRoutineName=MODL Daily
testrayServerURL=https://testray.liferay.com
testrayTeamName=Vale