buildscript {
	repositories {
		mavenLocal()

		maven {
			url "http://cdn.repository.liferay.com/nexus/content/groups/public"
		}
	}

	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.poshi.runner", version: "1.0.8"
	}
}

subprojects{
	apply plugin: "com.liferay.poshi.runner"

	poshiRunner {
		baseDir = file(".")
		version = "1.0.36"

		project.ext.testProperties = new Properties()

		List<File> poshiRunnerPropertiesFiles = new ArrayList<>()

		poshiRunnerPropertiesFiles.add(new File(rootProject.projectDir, "test.properties"))
		poshiRunnerPropertiesFiles.add(new File(baseDir, "test.properties"))

		poshiRunnerPropertiesFiles.each { poshiRunnerPropertiesFile ->
			if (poshiRunnerPropertiesFile.exists()) {
				testProperties.load(new FileInputStream(poshiRunnerPropertiesFile))
			}
		}

		setPoshiProperties testProperties
	}

	repositories {
		mavenLocal()

		maven {
			url "http://cdn.repository.liferay.com/nexus/content/groups/public"
		}
	}
}