<?xml version="1.0"?>

<project name="liferay-qa-website-ee"
	basedir="."
	default="compile"
	xmlns:antelope="antlib:ise.antelope.tasks"
	xmlns:artifact="antlib:org.apache.maven.artifact.ant"
	xmlns:if="ant:if"
	xmlns:unless="ant:unless"
>
	<import file="build-common.xml" />

	<path id="lib.classpath">
		<fileset dir="${basedir}/lib" includes="*.jar" />
	</path>

	<taskdef classpathref="lib.classpath" resource="ise/antelope/tasks/antlib.xml" uri="antlib:ise.antelope.tasks" />
	<taskdef classpathref="lib.classpath" resource="net/sf/antcontrib/antlib.xml" />
	<taskdef classpathref="lib.classpath" resource="com/liferay/source/formatter/ant/taskdefs.properties" />

	<target name="record-git-commit-websites">
		<exec executable="git" outputproperty="git.commit.websites.rev.parse">
			<arg line="rev-parse HEAD" />
		</exec>

		<echo file="git-commit-websites">${git.commit.websites.rev.parse}</echo>
	</target>

	<target name="format-source">
		<format-source />
	</target>
</project>