import de.undercouch.gradle.tasks.download.Download

import java.util.regex.Matcher

import org.gradle.internal.os.OperatingSystem

buildscript {
	repositories {
		maven {
			url "https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public"
		}

		maven {
			url "https://plugins.gradle.org/m2/"
		}
	}

	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.poshi.runner", version: "1.0.10"
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.source.formatter", version: "2.2.10"
		classpath group: "de.undercouch", name: "gradle-download-task", version: "3.2.0"
		classpath group: "net.saliman", name: "gradle-properties-plugin", version: "1.4.6"
	}
}

apply plugin: "net.saliman.properties"
apply plugin: "com.liferay.source.formatter"

task cleanWebDriver(type: Delete)
task downloadChromeDriver(type: Download)
task downloadInternetExplorerDriver(type: Download)
task unzipChromeDriver(type: Copy)
task unzipInternetExplorerDriver(type: Copy)

if (!hasProperty("operatingSystem")) {
	StringBuilder sb = new StringBuilder()

	OperatingSystem operatingSystem = OperatingSystem.current()

	if (operatingSystem.linux) {
		sb.append "linux"
	}
	else if (operatingSystem.macOsX) {
		sb.append "mac"
	}
	else if (operatingSystem.windows) {
		sb.append "windows"
	}
	else {
		throw new IllegalStateException("Unsupported operating system")
	}

	if (operatingSystem.toString().contains("64")) {
		sb.append "64"
	}
	else {
		sb.append "32"
	}

	ext.operatingSystem = sb.toString()
}

if (browser == "internet.explorer" && !operatingSystem.contains("win")) {
	throw new IllegalStateException("Internet Explorer is not supported on your operating system")
}

File webDriverRootDir = new File(buildDir, "webdriver")

allprojects {
	apply plugin: "net.saliman.properties"
}

cleanWebDriver {
	delete webDriverRootDir
}

downloadChromeDriver {
	dest new File(webDriverRootDir, "chromedriver/${chromeDriverVersion}/${operatingSystem}/chromedriver.zip")
	overwrite false
	src "https://chromedriver.storage.googleapis.com/${chromeDriverVersion}/chromedriver_${operatingSystem}.zip"
}

downloadInternetExplorerDriver {
	String ieDriverServerOs

	if (operatingSystem == "win64") {
		ieDriverServerOs = "x64"
	}
	else {
		ieDriverServerOs = "Win32"
	}

	dest new File(webDriverRootDir, "iedriver/${seleniumVersion}/${operatingSystem}/IEDriverServer_${ieDriverServerOs}_${seleniumVersion}.zip")
	overwrite false
	src "http://selenium-release.storage.googleapis.com/${_parseMajorVersion(seleniumVersion)}/IEDriverServer_${ieDriverServerOs}_${seleniumVersion}.zip"
}

unzipChromeDriver {
	dependsOn downloadChromeDriver
	from zipTree(downloadChromeDriver.dest)
	into new File(webDriverRootDir, "chromedriver/${chromeDriverVersion}/${operatingSystem}")
}

unzipInternetExplorerDriver {
	dependsOn downloadInternetExplorerDriver
	from zipTree(downloadInternetExplorerDriver.dest)
	into new File(webDriverRootDir, "iedriver/${seleniumVersion}/${operatingSystem}")
}

subprojects {
	apply plugin: "com.liferay.poshi.runner"

	clean {
		delete "test.case.method.names.properties"
		delete "test.generated.properties"
		delete "test-results"
		delete "tests"

		dependsOn cleanWebDriver
	}

	configurations {
		sikuliComplete
	}

	dependencies {
		["x86", "x86_64"].each {
			sikuliComplete classifier: "linux-${it}", group: "org.bytedeco.javacpp-presets", name: "opencv", version: poshiRunner.openCVVersion
			sikuliComplete classifier: "windows-${it}", group: "org.bytedeco.javacpp-presets", name: "opencv", version: poshiRunner.openCVVersion
		}

		sikuliComplete classifier: "macosx-x86_64", group: "org.bytedeco.javacpp-presets", name: "opencv", version: poshiRunner.openCVVersion
	}

	poshiRunner {
		baseDir = "test/functional"
		openCVVersion = "2.4.10-0.10"

		poshiProperties << _getTestProperties(project)
		poshiProperties.put "browser.type", browser.replaceAll("\\.", "")

		if (browser == "chrome") {
			poshiProperties.put "selenium.executable.dir.name", "${unzipChromeDriver.destinationDir}${File.separator}"
			poshiProperties.put "selenium.chrome.driver.executable", "chromedriver"
		}
		else if (browser == "internet.explorer") {
			poshiProperties.put "selenium.executable.dir.name", "${unzipInternetExplorerDriver.destinationDir}${File.separator}"
			poshiProperties.put "selenium.ie.driver.executable", "IEDriverServer.exe"
		}

		poshiPropertiesFile = rootProject.file("test.properties")
		version = "1.0.56"
	}

	repositories {
		maven {
			url "https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public"
		}
	}

	runPoshi {
		if (browser == "chrome") {
			dependsOn unzipChromeDriver
		}
		else if (browser == "internet.explorer") {
			dependsOn unzipInternetExplorerDriver
		}
	}
}

repositories {
	maven {
		url "https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public"
	}
}

private Properties _getCustomProperties(String prefix, Project project) {
	Properties properties = new Properties()

	List<String> testPropertiesFileNames = ["${prefix}.properties"]

	if (System.env.HOSTNAME) {
		testPropertiesFileNames << "${prefix}.${System.env.HOSTNAME}.properties"
	}

	if (System.env.HOST) {
		testPropertiesFileNames << "${prefix}.${System.env.HOST}.properties"
	}

	if (System.env.COMPUTERNAME) {
		testPropertiesFileNames << "${prefix}.${System.env.COMPUTERNAME}.properties"
	}

	if (System.env.USER) {
		testPropertiesFileNames << "${prefix}.${System.env.USER}.properties"
	}

	for (String testPropertiesFileName in testPropertiesFileNames) {
		File testPropertiesFile = new File(project.projectDir, testPropertiesFileName)

		if (testPropertiesFile.exists()) {
			properties << GUtil.loadProperties(testPropertiesFile)
		}
	}

	properties
}

private Properties _getTestProperties(Project project) {
	Properties properties = new Properties()

	properties << _getCustomProperties("test", rootProject)

	if (project != rootProject) {
		properties << _getCustomProperties("test", project)
	}

	properties
}

private String _parseMajorVersion(String version) {
	Matcher matcher = version =~ /^([0-9]+)\.([0-9]+).*/

	if (!matcher.matches()) {
		throw new IllegalArgumentException("${version} is not a valid version string")
	}

	"${matcher.group(1)}.${matcher.group(2)}"
}