buildscript {
	repositories {
		mavenLocal()

		maven {
			url "https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public"
		}
	}

	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.poshi.runner", version: "1.0.10"
	}
}

subprojects {
	apply plugin: "com.liferay.poshi.runner"

	poshiRunner {
		baseDir = "test/functional"

		File testPropertiesFile = file("test.properties")

		if (testPropertiesFile.exists()) {
			Properties testProperties = new Properties()

			testPropertiesFile.withInputStream {
				testProperties.load it
			}

			poshiProperties = testProperties
		}

		poshiPropertiesFile = rootProject.file("test.properties")
		version = "1.0.36"
	}

	repositories {
		mavenLocal()

		maven {
			url "https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public"
		}
	}
}