##
## Selenium
##

    selenium.logger.enabled=false

##
## Test Batch
##

    test.batch.group.ignore.regex=priority

    test.batch.max.subgroup.size=1000
    test.batch.max.group.size=1000

    test.batch.run.type=sequential


##
## Utilities
##

    get.location.max.retries=10
    project.dir=.
    selenium.logger.enabled=false
    test.base.dir.name=test
    test.console.log.file.name=poshiBugWorkaround
    #test.dependencies.dir.name=
    test.include.dir.names=../shared
    #test.run.locally=