##
## Selenium
##

    selenium.logger.enabled=false

##
## Test Batch
##

    test.batch.group.ignore.regex=priority

    test.batch.max.subgroup.size=1000
    test.batch.max.group.size=1000

    test.batch.names=qa-websites-functional-jdk8

    test.batch.run.type=sequential

    test.batch.spira.enabled[test-qa-websites-*]=true
    test.batch.spira.project.id[test-qa-websites-*]=12
    test.batch.spira.release.path[test-qa-websites-*]=/Liferay $(portal.profile) $(portal.version)/QA Websites/$(qa.websites.project.name)
    test.batch.spira.test.case.type[functional-*]=Poshi

    test.segment.enabled=true

##
## Testray
##

    testray.build.name=$(jenkins.job.name) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.product.version=1.x
    testray.routine.name=Upstream
    testray.server.url=https://webserver-testray-dev.lfr.cloud

##
## Utilities
##

    project.dir=.
    selenium.logger.enabled=false
    test.base.dir.name=testFunctional
    test.console.log.file.name=poshiBugWorkaround
    #test.dependencies.dir.name=
    test.include.dir.names=../shared
    #test.run.locally=