buildscript {
    repositories {
        if (System.getenv("JENKINS_HOME")) {
            ivy {
                layout "gradle"
                url ".ivy"
            }
        }
        else {
            jcenter()

            maven {
                url "https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public"
            }
            maven {
                url "https://plugins.gradle.org/m2/"
            }
        }
    }
    dependencies {
        classpath group: "com.liferay", name: "com.liferay.gradle.plugins.poshi.runner", version: "1.0.10"
        classpath group: "de.undercouch", name: "gradle-download-task", version: "3.2.0"
        classpath group: "net.saliman", name: "gradle-properties-plugin", version: "1.4.6"
        classpath group: "org.ysb33r.gradle", name: "ivypot", version: "0.4"
    }
}

import de.undercouch.gradle.tasks.download.Download
import org.gradle.internal.os.OperatingSystem

apply from: "properties.gradle"

ext {
    if (!project.hasProperty("operatingSystem")) {
        StringBuilder sb = new StringBuilder()

        if (OperatingSystem.current().isLinux()) {
            sb.append("linux")
        }
        else if (OperatingSystem.current().isMacOsX()) {
            sb.append("mac")
        }
        else if (OperatingSystem.current().isWindows()) {
            sb.append("windows")
        }
        else {
            throw new IllegalStateException("Unsupported operating system")
        }

        if (OperatingSystem.current().toString().contains("64")) {
            sb.append("64")
        }
        else {
            sb.append("32")
        }

        operatingSystem = sb.toString()
    }

    requireExternalWebDriver = browser == "chrome" || browser == "internet.explorer"
    webDriverRootDir = file("${buildDir}/webdriver")
}

allprojects {
    apply plugin: "net.saliman.properties"
    apply plugin: "org.ysb33r.ivypot"

    ext {
        if (browser == "chrome") {
            webDriverFolder = file("${webDriverRootDir}/chromedriver/${chromeDriverVersion}/${operatingSystem}")
            webDriverZip = "chromedriver.zip"
            webDriverExecutable = "chromedriver"
            webDriverURL = "https://chromedriver.storage.googleapis.com/${chromeDriverVersion}/chromedriver_${operatingSystem}.zip"
        }
        else if (browser == "internet.explorer") {
            String ieDriverServerOs

            if (operatingSystem == "win32") {
                ieDriverServerOs = "Win32"
            }
            else if (operatingSystem == "win64") {
                ieDriverServerOs = "x64"
            }
            else {
                throw new IllegalStateException("Internet Explorer is not supported on your operating system")
            }

            webDriverFolder = file("${webDriverRootDir}/iedriver/${seleniumVersion}/${operatingSystem}")
            webDriverExecutable = "IEDriverServer.exe"
            webDriverZip = "IEDriverServer_${ieDriverServerOs}_${seleniumVersion}.zip"
            webDriverURL = "http://selenium-release.storage.googleapis.com/${parseMajorVersion(seleniumVersion)}/${webDriverZip}"
        }
    }
}

if (requireExternalWebDriver) {
    task downloadWebDriver(type: Download) {
        src webDriverURL
        dest "${webDriverFolder}/${webDriverZip}"
        overwrite false
    }

    task unzipWebDriver(type: Copy, dependsOn: downloadWebDriver) {
        from zipTree(file("${webDriverFolder}/${webDriverZip}"))
        into file(webDriverFolder)
    }

    task cleanWebDriver(type: Delete) {
        delete webDriverRootDir
    }
}

subprojects {
    apply plugin: "com.liferay.poshi.runner"

    clean {
        if (requireExternalWebDriver) {
            clean.dependsOn cleanWebDriver
        }
    }

    poshiRunner {
        baseDir = "test/functional"
        poshiProperties << getTestProperties(project)
        poshiProperties.put("browser.type", browser.replaceAll("\\.", ""))
        poshiPropertiesFile = rootProject.file("test.properties")
        openCVVersion = "2.4.10-0.10"
        version = "1.0.56"

        if (requireExternalWebDriver) {
            poshiProperties.put("selenium.executable.dir.name", "${webDriverFolder}${File.separator}")
        }

        if (browser == "chrome") {
            poshiProperties.put("selenium.chrome.driver.executable", webDriverExecutable)
        }
        else if (browser == "internet.explorer") {
            poshiProperties.put("selenium.ie.driver.executable", webDriverExecutable)
        }
    }

    if (requireExternalWebDriver) {
        runPoshi.dependsOn unzipWebDriver
    }
}
