#ivy cached data file for com.github.scribejava#scribejava;3.2.0
#Thu Jan 05 15:28:30 PST 2017
artifact\:ivy\#ivy\#xml\#293083568.is-local=false
artifact\:ivy\#ivy\#xml\#293083568.location=https\://plugins.gradle.org/m2/com/github/scribejava/scribejava/3.2.0/scribejava-3.2.0.pom
artifact.resolver=maven
artifact\:scribejava\#pom.original\#pom\#498856493.location=https\://plugins.gradle.org/m2/com/github/scribejava/scribejava/3.2.0/scribejava-3.2.0.pom
artifact\:scribejava\#pom.original\#pom\#498856493.is-local=false
resolver=maven
