#ivy cached data file for org.apache.ivy#ivy;2.4.0
#Fri Sep 16 11:55:13 PDT 2016
artifact\:ivy\#jar\#jar\#640748172.is-local=false
artifact\:ivy\#jar\#jar\#640748172.location=https\://plugins.gradle.org/m2/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar
artifact.resolver=maven
artifact\:ivy\#pom.original\#pom\#-2001656462.location=https\://plugins.gradle.org/m2/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.pom
artifact\:ivy\#ivy\#xml\#640333365.location=https\://plugins.gradle.org/m2/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.pom
artifact\:ivy\#ivy\#xml\#640333365.is-local=false
artifact\:ivy\#pom.original\#pom\#-2001656462.is-local=false
resolver=maven
