##
## Component Names
##

    component.names=analytics-cloud

##
## ACSE Account Properties
##

    demo.user.name.1=
    demo.user.name.2=


    demo.user.password.1=test
    demo.user.password.2=test


##
## Testray
##

    testray.project.name=Analytics Cloud

##
## Test Batch
##

    test.batch.property.query=true

##
## Testray
##

    testray.project.name=Analytics Cloud