#ivy cached data file for com.liferay#com.liferay.poshi.runner;1.0.54
#Wed May 03 08:43:34 PDT 2017
resolver=maven
artifact\:com.liferay.poshi.runner\#pom.original\#pom\#-1539071274.is-local=false
artifact\:com.liferay.poshi.runner\#pom.original\#pom\#-1539071274.location=https\://plugins.gradle.org/m2/com/liferay/com.liferay.poshi.runner/1.0.54/com.liferay.poshi.runner-1.0.54.pom
artifact\:com.liferay.poshi.runner\#jar\#jar\#1103333360.is-local=false
artifact\:ivy\#ivy\#xml\#-560097889.location=https\://plugins.gradle.org/m2/com/liferay/com.liferay.poshi.runner/1.0.54/com.liferay.poshi.runner-1.0.54.pom
artifact\:com.liferay.poshi.runner\#jar\#jar\#1103333360.location=https\://plugins.gradle.org/m2/com/liferay/com.liferay.poshi.runner/1.0.54/com.liferay.poshi.runner-1.0.54.jar
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-560097889.is-local=false
artifact\:com.liferay.poshi.runner\#source\#jar\#-1548074626.location=https\://plugins.gradle.org/m2/com/liferay/com.liferay.poshi.runner/1.0.54/com.liferay.poshi.runner-1.0.54-sources.jar
artifact\:com.liferay.poshi.runner\#source\#jar\#-1548074626.is-local=false
