#ivy cached data file for com.liferay#com.liferay.poshi.runner;1.0.56
#Thu Sep 21 18:55:39 PDT 2017
artifact\:ivy\#ivy\#xml\#-560085383.location=https\://plugins.gradle.org/m2/com/liferay/com.liferay.poshi.runner/1.0.56/com.liferay.poshi.runner-1.0.56.pom
artifact\:com.liferay.poshi.runner\#pom.original\#pom\#-1539058768.is-local=false
artifact\:com.liferay.poshi.runner\#jar\#jar\#1103345866.is-local=false
artifact\:com.liferay.poshi.runner\#pom.original\#pom\#-1539058768.location=https\://plugins.gradle.org/m2/com/liferay/com.liferay.poshi.runner/1.0.56/com.liferay.poshi.runner-1.0.56.pom
resolver=maven
artifact\:com.liferay.poshi.runner\#source\#jar\#-1548062120.is-local=false
artifact\:ivy\#ivy\#xml\#-560085383.is-local=false
artifact\:com.liferay.poshi.runner\#source\#jar\#-1548062120.location=https\://plugins.gradle.org/m2/com/liferay/com.liferay.poshi.runner/1.0.56/com.liferay.poshi.runner-1.0.56-sources.jar
artifact.resolver=maven
artifact\:com.liferay.poshi.runner\#jar\#jar\#1103345866.location=https\://plugins.gradle.org/m2/com/liferay/com.liferay.poshi.runner/1.0.56/com.liferay.poshi.runner-1.0.56.jar
