#ivy cached data file for com.liferay#com.liferay.poshi.runner;1.0.36
#Wed Jun 22 11:43:53 PDT 2016
artifact\:com.liferay.poshi.runner\#javadoc\#jar\#1451504991.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.poshi.runner/1.0.36/com.liferay.poshi.runner-1.0.36-javadoc.jar
artifact\:com.liferay.poshi.runner\#jar\#jar\#1102958180.is-local=false
artifact\:com.liferay.poshi.runner\#pom.original\#pom\#-1539446454.is-local=false
artifact\:ivy\#ivy\#xml\#-560473069.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.poshi.runner/1.0.36/com.liferay.poshi.runner-1.0.36.pom
artifact\:com.liferay.poshi.runner\#javadoc\#jar\#1451504991.is-local=false
resolver=maven
artifact\:ivy\#ivy\#xml\#-560473069.is-local=false
artifact\:com.liferay.poshi.runner\#source\#jar\#-1548449806.is-local=false
artifact\:com.liferay.poshi.runner\#source\#jar\#-1548449806.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.poshi.runner/1.0.36/com.liferay.poshi.runner-1.0.36-sources.jar
artifact.resolver=maven
artifact\:com.liferay.poshi.runner\#jar\#jar\#1102958180.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.poshi.runner/1.0.36/com.liferay.poshi.runner-1.0.36.jar
artifact\:com.liferay.poshi.runner\#pom.original\#pom\#-1539446454.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.poshi.runner/1.0.36/com.liferay.poshi.runner-1.0.36.pom
