#ivy cached data file for com.google.guava#guava;19.0
#Wed Oct 19 10:24:42 PDT 2016
artifact\:guava\#bundle\#jar\#2036612289.location=https\://plugins.gradle.org/m2/com/google/guava/guava/19.0/guava-19.0.jar
artifact\:guava\#bundle\#jar\#2036612289.is-local=false
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#1169619513.is-local=false
artifact\:ivy\#ivy\#xml\#1169619513.location=https\://plugins.gradle.org/m2/com/google/guava/guava/19.0/guava-19.0.pom
artifact\:guava\#pom.original\#pom\#367725272.location=https\://plugins.gradle.org/m2/com/google/guava/guava/19.0/guava-19.0.pom
resolver=maven
artifact\:guava\#pom.original\#pom\#367725272.is-local=false
