#ivy cached data file for org.seleniumhq.selenium#selenium-edge-driver;2.47.1
#Wed Jun 22 11:43:53 PDT 2016
artifact\:selenium-edge-driver\#pom.original\#pom\#-1872629957.is-local=false
artifact\:selenium-edge-driver\#pom.original\#pom\#-1872629957.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-edge-driver/2.47.1/selenium-edge-driver-2.47.1.pom
artifact\:ivy\#ivy\#xml\#-1558357591.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-edge-driver/2.47.1/selenium-edge-driver-2.47.1.pom
artifact\:ivy\#ivy\#xml\#-1558357591.is-local=false
artifact.resolver=maven
artifact\:selenium-edge-driver\#jar\#jar\#769774677.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-edge-driver/2.47.1/selenium-edge-driver-2.47.1.jar
artifact\:selenium-edge-driver\#jar\#jar\#769774677.is-local=false
resolver=maven
