#ivy cached data file for org.seleniumhq.selenium#selenium-edge-driver;2.53.0
#Fri Sep 16 11:55:13 PDT 2016
artifact\:selenium-edge-driver\#jar\#jar\#932015015.is-local=false
artifact\:ivy\#ivy\#xml\#-1396117253.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-edge-driver/2.53.0/selenium-edge-driver-2.53.0.pom
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-1396117253.is-local=false
artifact\:selenium-edge-driver\#pom.original\#pom\#-1710389619.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-edge-driver/2.53.0/selenium-edge-driver-2.53.0.pom
artifact\:selenium-edge-driver\#pom.original\#pom\#-1710389619.is-local=false
resolver=maven
artifact\:selenium-edge-driver\#jar\#jar\#932015015.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-edge-driver/2.53.0/selenium-edge-driver-2.53.0.jar
