##
## Account Properties
##
    patcher.admin.email.address=test@liferay.com
    patcher.admin.password=liferay

    zendesk.admin.email.address=zendesk.admin@liferay.com.broken
    zendesk.admin.password=zendeskqauser

    zendesk.api.token=H5vC4cxSZdgZdKYVTDNPdmTKXqVUeQAmUWxVfIC4

##
## Component Names
##

    component.names=patcher-portal

##
## Test Batch
##

    test.batch.property.query=true

##
## Testray
##

    testray.project.name=Patcher

##
## Test Properties
##

    build.compile.completion.poll.interval.in.minutes=7
    build.merge.completion.poll.interval.in.seconds=10
    build.rebase.completion.poll.interval.in.seconds=10
    build.completion.poll.maximum.iterations=15

    fix.completion.poll.interval.in.seconds=30
    fix.completion.poll.maximum.iterations=15

    portal.url=http://cloud-10-50-0-130

	zendesk.liferay.url=https://liferaysupport1528999723.zendesk.com