##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    line.length.excludes=\
<<<<<<< HEAD
        modules/apps/site/site-teams-web/src/main/java/com/liferay/site/teams/web/internal/display/context/EditSiteTeamAssignmentsUserGroupsManagementToolbarDisplayContext.java@139
=======
        modules/apps/site/site-teams-web/src/main/java/com/liferay/site/teams/web/internal/display/context/EditSiteTeamAssignmentsUserGroupsManagementToolbarDisplayContext.java@133
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
