app.marketplace.id=31718422
app.marketplace.title=Liferay CE Notifications
<<<<<<< HEAD
app.marketplace.version=6.0.1
app.portal.build=7400
=======
app.marketplace.version=5.0.5
app.portal.build=7306
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
