#ivy cached data file for cglib#cglib;3.1
#Wed Oct 19 10:24:42 PDT 2016
artifact\:cglib\#jar\#jar\#-1011737555.is-local=false
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-1532961303.is-local=false
artifact\:ivy\#ivy\#xml\#-1532961303.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/cglib/cglib/3.1/cglib-3.1.pom
artifact\:cglib\#jar\#jar\#-1011737555.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/cglib/cglib/3.1/cglib-3.1.jar
resolver=maven
artifact\:cglib\#pom.original\#pom\#640825107.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/cglib/cglib/3.1/cglib-3.1.pom
artifact\:cglib\#pom.original\#pom\#640825107.is-local=false
