##
## Component Names
##

    component.names=partner

##
## Partner/Salesforce Account Properties
##

    partner.email.address.admin=test@liferay.com
    partner.email.password.admin=Testtest1
    partner.email.address.alliance_manager=douglas.simon=liferay.com@example.com
    partner.email.password.alliance_manager=test
    partner.email.address.general_manager=joshua.asbury@liferay.com.broken
    partner.email.password.general_manager=test
    partner.email.address.global_partner_marketing=karen.newnam@liferay.com.broken
    partner.email.password.global_partner_marketing=test
    partner.email.address.partner=johnnie.stubbs@arcusys.com.broken
    partner.email.password.partner=test
    partner.email.address.partner2=katy.roby@arcusys.com.broken
    partner.email.password.partner2=test
    partner.email.address.regional_finance=accounts@liferay.com.broken
    partner.email.password.regional_finance=test
    salesforce.email.address.qa=is-sales-qa@liferay.com.qa
    salesforce.email.password.qa=l1f3ray151
    salesforce.email.address.sales3=is-sales-qa@liferay.com.sales3
    salesforce.email.password.sales3=l1f3ray151

##
## Testray
##

    testray.project.name=Partner

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == "partner" AND known-issues == null

##
## Test Case
##

    test.case.available.property.names=testray.main.component.name

##
## Utilities
##

    portal.partner.url=https://partner-uat.liferay.com
    portal.sales.url=https://test.salesforce.com/
    test.include.dir.names=\
        ../marketplace/testFunctional,\
        ../osb/testFunctional,\
        ../salesforce/testFunctional,\
        ../shared