##
## Component Names
##

    component.names=partner

##
## Salesforce Account Properties
##

    partner.email.address.admin=test@liferay.com
    partner.email.password.admin=test1234
    partner.email.address.alliance_manager=douglas.simon=liferay.com@example.com
    partner.email.password.alliance_manager=test
    partner.email.address.general_manager=joshua.asbury@liferay.com.broken
    partner.email.password.general_manager=test
    partner.email.address.global_partner_marketing=karen.newnam@liferay.com.broken
    partner.email.password.global_partner_marketing=test
    partner.email.address.partner=johnnie.stubbs@arcusys.com.broken
    partner.email.password.partner=test
    partner.email.address.regional_finance=accounts@liferay.com.broken
    partner.email.password.regional_finance=test

##
## Testray
##

    testray.project.name=Partner

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == "partner" AND known-issues == null

##
## Test Case
##

    test.case.available.property.names=testray.main.component.name

##
## Utilities
##

    portal.url=https://partner-uat.liferay.com
    test.include.dir.names=\
      ../shared

