##
## Component Names
##

    component.names=partner

##
## Partner/Salesforce Account Properties
##

    partner.company=Base22, LLC
    partner.region=United States
    partner.region.code=us

    #partner.company=Ancud IT - Beratung GmbH
    #partner.region=Germany
    #partner.region.code=dach

    #partner.company=ARHS Developments Belgium
    #partner.region=Belgium
    #partner.region.code=benelux

    #partner.company=Canon Marketing Japan
    #partner.region=Japan
    #partner.region.code=japan

    #partner.company=INFORMATICA EL CORTE INGLES S.A. (IECISA)
    #partner.region=Spain
    #partner.region.code=spainportugal

    partner.email.address.admin=test@liferay.com
    partner.email.password.admin=Testtest1

    partner.email.address.global_alliance_manager=glenn.saler@liferay.com.broken
    partner.name.global_alliance_manager=Glenn Saler
    partner.userID.global_alliance_manager=Hh4JQaz3519eNJUldBZ43w%3D%3D

    partner.email.address.global_partner_marketing=glenn.saler@liferay.com.broken
    partner.name.global_partner_marketing=Glenn Saler
    partner.userID.global_partner_marketing=Hh4JQaz3519eNJUldBZ43w%3D%3D

    partner.us.email.address.alliance_manager=douglas.simon@liferay.com.broken
    partner.us.name.alliance_manager=Douglas Simon
    partner.us.userID.alliance_manager=ICUFyOnweSsq6QsDK1LvYg%3D%3D
    partner.japan.name.alliance_manager=Kota Namiki
    partner.japan.userID.alliance_manager=MYL0%2BiZjHdxGl6rJL4ILCw%3D%3D
    partner.dach.name.alliance_manager=Eguino Braganca
    partner.dach.userID.alliance_manager=et2E7dAiayN1LRYiFYyomg%3D%3D
    partner.benelux.name.alliance_manager=Koen van Dillen
    partner.benelux.userID.alliance_manager=v0Xn%2FGdlVzxJxr4s65hJsA%3D%3D
    partner.chpearurpa.name.alliance_manager=Valeria Vich
    partner.chpearurpa.userID.alliance_manager=3U%2FXqvrVK0hbUf2hjU6hHA%3D%3D
    partner.spainportugal.name.alliance_manager=Miguel Angel Echeverria
    partner.spainportugal.userID.alliance_manager=hqQVVkd24PB8JXFhA8t6QQ%3D%3D

    partner.us.email.address.general_manager=joshua.asbury@liferay.com.broken
    partner.us.name.general_manager=Joshua Asbury
    partner.us.userID.general_manager=cetNZP62X1pbRTgaxX9T2A%3D%3D
    partner.japan.name.general_manager=Craig Kaneko
    partner.japan.userID.general_manager=3kN98Vb2rEFaEY%2FNu24Pyg%3D%3D
    partner.dach.name.general_manager=Hans Bayer
    partner.dach.userID.general_manager=SMipcfopTAEoPP10ulzOew%3D%3D
    partner.benelux.name.general_manager=Ruud Kluivers
    partner.benelux.userID.general_manager=uwlEhi%2FVDgzZmt6NELYNBQ%3D%3D
    partner.chpearurpa.name.general_manager=Leonardo Granja
    partner.chpearurpa.userID.general_manager=M41tmloDXFi3U68I0Woovg%3D%3D
    partner.spainportugal.name.general_manager=Carolina Moreno
    partner.spainportugal.userID.general_manager=xaAM%2BORjeAV6rLgqyBCmMA%3D%3D

    partner.us.email.address.regional_field_marketing=michelle.hoshi@liferay.com.broken
    partner.us.name.regional_field_marketing=Michelle Hoshi
    partner.us.userID.regional_field_marketing=aL6dT2vIUkhI9TLupO8t7g%3D%3D
    partner.japan.name.regional_field_marketing=Eriko Gardiner
    partner.japan.userID.regional_field_marketing=YMfUi0QXZtzyIrVA42PBaQ%3D%3D
    partner.dach.name.regional_field_marketing=Annika Sinnecker
    partner.dach.userID.regional_field_marketing=k6AHzcq81GpEVzKx7rM5UQ%3D%3D
    partner.benelux.name.regional_field_marketing=Yvette Hooijmans
    partner.benelux.userID.regional_field_marketing=%2BSclwiEAdEugU8qM9z42iw%3D%3D
    partner.chpearurpa.name.regional_field_marketing=Daniela Lugo
    partner.chpearurpa.userID.regional_field_marketing=UscwetFhUqfJM8Aw9gf5YA%3D%3D
    partner.spainportugal.name.regional_field_marketing=Maria Sanchez
    partner.spainportugal.userID.regional_field_marketing=5ui3H7Bio%2BYOq3FfVUsYtQ%3D%3D

    partner.us.email.address.regional_finance=accounts@liferay.com.broken
    partner.us.name.regional_finance=Liferay Accounts
    partner.us.userID.regional_finance=azValZR7CAGpFcr2Lf49iQ%3D%3D
    partner.japan.name.regional_finance=Maki Park
    partner.japan.userID.regional_finance=w0BaLsij3h1fM%2BijDM71fw%3D%3D
    partner.dach.name.regional_finance=Quentin Duquesnois
    partner.dach.userID.regional_finance=icjDbh5RTDmnG2nli23j7A%3D%3D
    partner.benelux.name.regional_finance=Liferay Accounts IE
    partner.benelux.userID.regional_finance=UAydaCD%2Fy9DuRyFmUiY5Nw%3D%3D
    partner.chpearurpa.name.regional_finance=Financeiro Br
    partner.chpearurpa.userID.regional_finance=
    partner.spainportugal.name.regional_finance=Liferay Accounts IE
    partner.spainportugal.userID.regional_finance=UAydaCD%2Fy9DuRyFmUiY5Nw%3D%3D

    partner.us.email.address.partner=marco@base22.com.broken
    partner.us.name.partner=Marco Balderas
    partner.us.userID.partner=gcTc3BbY%2BlvX51UIvyvigA%3D%3D
    partner.japan.name.partner=Yukitaka Machida
    partner.japan.userID.partner=86nu8nbfHtBNVoS7nDm4hQ%3D%3D
    partner.dach.name.partner=Bernd Seifert
    partner.dach.userID.partner=95di75kNpOVk1cYzGxMuTA%3D%3D
    partner.benelux.name.partner=Armand Beuvens
    partner.benelux.userID.partner=48HgfFb7sNPprJlRVVzi7A%3D%3D
    partner.chpearurpa.name.partner=
    partner.chpearurpa.userID.partner=
    partner.spainportugal.name.partner=Juan Perez
    partner.spainportugal.userID.partner=TGtq%2FlGqyShjhvP8Vi2%2Fhg%3D%3D

    partner.us.email.address.partner2=mike@base22.com.broken
    partner.us.name.partner2=Mike Minardi
    partner.us.userID.partner2=WqJlQUJ53aPFYyROpCn7BA%3D%3D
    partner.japan.name.partner2=Yuki Kaneko
    partner.japan.userID.partner2=9ZbLciFH4i2hu9DBF%2Fdo4w%3D%3D
    partner.dach.name.partner2=Martin Bazan
    partner.dach.userID.partner2=LVt94nCTiitEzYqImIaZuQ%3D%3D
    partner.benelux.name.partner2=Antoine Huberland
    partner.benelux.userID.partner2=iq4bu2jp2RqfE1Z1rZcGcw%3D%3D
    partner.chpearurpa.name.partner2=
    partner.chpearurpa.userID.partner2=
    partner.spainportugal.name.partner2=Ernesto Muñoz Rodriguez
    partner.spainportugal.userID.partner2=Pov7mNFqUp%2B83P%2BAgLsC7A%3D%3D

    salesforce.email.address.qa=is-sales-qa@liferay.com.qa
    salesforce.email.password.qa=l1f3ray151
    salesforce.email.address.sales3=is-sales-qa@liferay.com.sales3
    salesforce.email.password.sales3=l1f3ray151

##
## Testray
##

    testray.project.name=Partner

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == "partner" AND known-issues == null

##
## Test Case
##

    test.case.available.property.names=testray.main.component.name

##
## Utilities
##

    portal.partner.url=https://partner-uat.liferay.com
    portal.mock.url=http://cloud-10-50-0-37:8282/
    portal.sales.url=https://test.salesforce.com/
    test.include.dir.names=\
        ../marketplace/testFunctional,\
        ../osb/testFunctional,\
        ../salesforce/testFunctional,\
        ../shared