#ivy cached data file for org.bytedeco#javacpp-presets;0.10
#Wed Oct 19 10:24:24 PDT 2016
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-322320458.location=https\://plugins.gradle.org/m2/org/bytedeco/javacpp-presets/0.10/javacpp-presets-0.10.pom
artifact\:ivy\#ivy\#xml\#-322320458.is-local=false
resolver=maven
artifact\:javacpp-presets\#pom.original\#pom\#1385220239.location=https\://plugins.gradle.org/m2/org/bytedeco/javacpp-presets/0.10/javacpp-presets-0.10.pom
artifact\:javacpp-presets\#pom.original\#pom\#1385220239.is-local=false
