##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Cosette'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Cosette')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Cosette')

##
## Poshi
##

    portal.url=http://test.azor.com

    save.screenshot=false

    test.base.dir.name=testFunctional/
    
    test.case.available.property.names=\
        testray.main.component.name

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.cosette.azor.portal.url.uat=http://test.azor.com
    test.this.cosette.benicar.portal.url.uat=http://test.benicar.com
    test.this.cosette.tribenzor.portal.url.uat=http://test.tribenzor.com
    test.this.cosette.welchol.portal.url.uat=http://test.welchol.com
    test.this.cosette.welcholhcp.portal.url.uat=http://test.welcholhcp.com
    
    test.this.cosette.portal.url.prod=http://<project-prod-url-tbd>

    test.this.cosette.test.account.uat.admin.login=<uat-admin-login-tbd>
    test.this.cosette.test.account.uat.admin.password=<uat-admin-password-tbd>
    
    test.this.cosette.test.account.uat.user.login=<uat-user-login-tbd>
    test.this.cosette.test.account.uat.user.password=<uat-user-password-tbd>

##
## Testray
##

    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.project.name=LXC

    testray.routine.name[uat]=MODL Daily