##
## CI
##

    component.names=<project-name>

    test.batch.property.query=testray.main.component.name == 'Project Name'

##
## Poshi
##

    portal.url=http://<project-uat-url>

    save.screenshot=false

    test.base.dir.name=testFunctional/
    
    test.case.available.property.names=\
        testray.main.component.name

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.projectname.portal.url.uat=http://<project-uat-url>
    test.this.projectname.portal.url.prod=http://<project-prod-url>

    test.this.projectname.test.account.uat.admin.login=<uat-admin-login>
    test.this.projectname.test.account.uat.admin.password=<uat-admin-password>
    
    test.this.projectname.test.account.uat.user.login=<uat-user-login>
    test.this.projectname.test.account.uat.user.password=<uat-user-password>

##
## Testray
##

    testray.project.name=<project-name>