#ivy cached data file for org.seleniumhq.selenium#selenium-leg-rc;2.53.0
#Wed Oct 19 10:24:42 PDT 2016
artifact\:ivy\#ivy\#xml\#-471129993.is-local=false
artifact.resolver=maven
artifact\:selenium-leg-rc\#jar\#jar\#-1323977719.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-leg-rc/2.53.0/selenium-leg-rc-2.53.0.jar
artifact\:selenium-leg-rc\#jar\#jar\#-1323977719.is-local=false
artifact\:selenium-leg-rc\#pom.original\#pom\#328584943.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-leg-rc/2.53.0/selenium-leg-rc-2.53.0.pom
resolver=maven
artifact\:selenium-leg-rc\#pom.original\#pom\#328584943.is-local=false
artifact\:ivy\#ivy\#xml\#-471129993.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-leg-rc/2.53.0/selenium-leg-rc-2.53.0.pom
