<<<<<<< HEAD
artifact.git.id=ca876212ed586fd7537d6d9e539d8563c6eec8ab
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/plugins/tasks-portlet/7.4.10.1/tasks-portlet-7.4.10.1.war
=======
artifact.git.id=6475b2f830f99b552fab1b2fdebd39f384bc3f17
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/plugins/tasks-portlet/7.3.10.25/tasks-portlet-7.3.10.25.war
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
