##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Customer Portal 2.0'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Customer Portal 2.0')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Customer Portal 2.0')

##
## Poshi
##

    portal.url=https://support-uat.lxc.liferay.com

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.projectname.portal.url.uat=https://support-uat.lxc.liferay.com
    test.this.projectname.portal.url.prod=https://support.liferay.com

    test.this.projectname.test.account.uat.admin.login=dbace26d5dadb9eed597@uat.com.broken
    test.this.projectname.test.account.uat.admin.password=q4F63ZEH3njnnA34S761

    test.this.projectname.test.account.uat.user.login=<uat-user-login>
    test.this.projectname.test.account.uat.user.password=<uat-user-password>

##
## Testray
##

    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.project.name=Solutions

    testray.routine.name[uat]=[lxc] ci:test:osb-site-initializer-customer-portal