environmentBrowserName=Google Chrome 100
environmentOperatingSystemName=Ubuntu 22.04.1
projectDir=.
testrayBuildName=support.liferay.com - $(start.time)
testrayCasePriority=1
testrayComponentName=Customer Portal 2.0
testrayProductVersion=1.x
testrayProjectName=Solutions
testrayRoutineName=[lxc] ci:test:osb-site-initializer-customer-portal
testrayServerURL=https://testray.liferay.com
testrayTeamName=Customer Portal 2.0