##
## Component Names
##

    component.names=salesforce

##
## Salesforce Account Properties
##

    salesforce.email.address=is-sales-qa@liferay.com.qa

    salesforce.email.password=l1f3ray151

##
## Testray
##

    testray.project.name=Salesforce

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == "salesforce" AND known-issues == null

##
## Test Case
##

    test.case.available.property.names=testray.main.component.name

##
## Utilities
##

    portal.url=https://test.salesforce.com/