##
## CI
##

    test.batch.property.query=true

    test.batch.property.query[smoke]=\
        (testray.main.component.name == 'Smoke')

    test.batch.group.ignore.regex=testray.main.component.name


##
## Poshi
##

    portal.url=http://console.liferay.coffee/

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

##
## Testray
##

    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.project.name=Liferay Cloud Platform
    testray.routine.name=Development Daily

    testray.team.names=\
        core,\
        search

    testray.team.core.component.names=\
        Smoke

    testray.team.search.component.names=\
        Search