##
## Component Names
##

    component.names=liferay-cloud-platform

##
## Portal URL
##

    portal.url=http://console.liferay.coffee/

##
## Test Base
##

    test.base.dir.name=testFunctional/

##
## Test Batch
##

    test.batch.property.query=\
        (testray.main.component.name == 'Liferay Cloud Platform')

##
## Test Case
##

    test.case.available.property.names=\
        testray.main.component.name

    test.case.available.property.values[testray.main.component.name]=\
        ${testray.team.liferay-cloud-platform.component.names}

    testray.team.names=\
        liferay-cloud-platform

    testray.team.liferay-cloud-platform.component.names=\
        Liferay Cloud Platform

##
## Testray
##

    testray.project.name=Liferay Cloud Platform
    testray.routine.name=Development Daily
    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)