##
## CI
##

    browser.chrome.bin.args=\
        disable-dev-shm-usage \
        disable-gpu \
        password-store=basic

    component.names=liferay-cloud-platform

    test.batch.property.query=true

    test.batch.property.query[smoke]=\
        (testray.main.component.name == 'Liferay Cloud Platform')

    test.batch.group.ignore.regex=testray.main.component.name

##
## Poshi
##

    test.case.available.property.names=\
        testray.main.component.name

    test.dirs=testFunctional/

##
## Test This
##

    test.this.account.guest.user1.email=qaposhiuser1@test.com
    test.this.account.guest.user1.password=K4@igE8B3n95$l
    test.this.account.guest.user2.email=qaposhiuser2@test.com
    test.this.account.guest.user2.password=i0ZHut06,fvn&0f
    test.this.account.guest.user3.email=qaposhiuser3@test.com
    test.this.account.guest.user3.password=p3e^wsyjIH75$9R
    test.this.account.guest.user4.email=qaposhiuser4@test.com
    test.this.account.guest.user4.password=4SEO8^RxEv8D.cR
    test.this.lcp.test.account.guest.user.email=poshi.guest@liferay.cloud
    test.this.lcp.test.account.guest.user.password=fK21K*L1F3rLHj&3@
    test.this.lcp.test.account.user.email=poshi.tester@liferay.cloud
    test.this.lcp.test.account.user.password=Ra*5Te$K7RAYm72m
    test.this.lcp.test.base.url.api=api.liferay.coffee

##
## Testray
##

    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.project.name=Liferay Cloud Platform
    testray.routine.name=Development Daily

    testray.team.names=\
        cloud

    testray.team.cloud.component.names=\
        liferay-cloud-platform