#ivy cached data file for org.apache.httpcomponents#httpcore;4.4.1
#Wed Jun 22 11:43:53 PDT 2016
artifact\:ivy\#ivy\#xml\#-726814922.is-local=false
artifact\:httpcore\#pom.original\#pom\#-401064714.is-local=false
artifact\:httpcore\#pom.original\#pom\#-401064714.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpcore/4.4.1/httpcore-4.4.1.pom
artifact.resolver=maven
artifact\:httpcore\#jar\#jar\#-2053627376.is-local=false
artifact\:httpcore\#jar\#jar\#-2053627376.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpcore/4.4.1/httpcore-4.4.1.jar
artifact\:ivy\#ivy\#xml\#-726814922.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpcore/4.4.1/httpcore-4.4.1.pom
resolver=maven
