#ivy cached data file for org.apache.httpcomponents#httpcore;4.4.4
#Thu Sep 21 18:55:20 PDT 2017
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-726796163.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.pom
artifact\:ivy\#ivy\#xml\#-726796163.is-local=false
artifact\:httpcore\#jar\#jar\#-2053608617.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar
artifact\:httpcore\#pom.original\#pom\#-401045955.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.pom
artifact\:httpcore\#pom.original\#pom\#-401045955.is-local=false
resolver=maven
artifact\:httpcore\#jar\#jar\#-2053608617.is-local=false
