#ivy cached data file for org.apache.httpcomponents#httpcore;4.4.3
#Wed Oct 19 10:24:42 PDT 2016
artifact\:httpcore\#pom.original\#pom\#-401052208.is-local=false
artifact\:httpcore\#jar\#jar\#-2053614870.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.4.3/httpcore-4.4.3.jar
artifact.resolver=maven
artifact\:httpcore\#jar\#jar\#-2053614870.is-local=false
resolver=maven
artifact\:httpcore\#pom.original\#pom\#-401052208.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.4.3/httpcore-4.4.3.pom
artifact\:ivy\#ivy\#xml\#-726802416.is-local=false
artifact\:ivy\#ivy\#xml\#-726802416.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.4.3/httpcore-4.4.3.pom
