app.marketplace.id=125667217
app.marketplace.title=Liferay CE Portal Security SSO Google
<<<<<<< HEAD
app.marketplace.version=3.0.0
app.portal.build=7400
=======
app.marketplace.version=2.0.0
app.portal.build=7306
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
