#ivy cached data file for javax.activation#activation;1.1
#Fri Sep 16 11:55:13 PDT 2016
artifact\:activation\#jar\#jar\#-152915764.is-local=false
artifact\:activation\#pom.original\#pom\#1499646898.is-local=false
artifact\:activation\#pom.original\#pom\#1499646898.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/javax/activation/activation/1.1/activation-1.1.pom
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#1587205083.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/javax/activation/activation/1.1/activation-1.1.pom
resolver=maven
artifact\:ivy\#ivy\#xml\#1587205083.is-local=false
artifact\:activation\#jar\#jar\#-152915764.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/javax/activation/activation/1.1/activation-1.1.jar
