plugin.notifications.enabled=false

jdbc.default.jndi.name=

jdbc.default.driverClassName=com.mysql.jdbc.Driver
jdbc.default.url=jdbc:mysql://localhost/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
jdbc.default.username=
jdbc.default.password=

liferay.home=

captcha.max.challenges=0

browser.launcher.url=

#index.on.startup=true

mail.session.jndi.name=

axis.servlet.hosts.allowed=

setup.wizard.enabled=false
terms.of.use.required=false

tunnel.servlet.hosts.allowed=