#ivy cached data file for org.seleniumhq.selenium#selenium-ie-driver;2.53.0
#Fri Sep 16 11:55:13 PDT 2016
artifact\:selenium-ie-driver\#jar\#jar\#-696524742.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-ie-driver/2.53.0/selenium-ie-driver-2.53.0.jar
artifact\:ivy\#ivy\#xml\#1716070453.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-ie-driver/2.53.0/selenium-ie-driver-2.53.0.pom
artifact\:ivy\#ivy\#xml\#1716070453.is-local=false
artifact\:selenium-ie-driver\#pom.original\#pom\#956037920.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-ie-driver/2.53.0/selenium-ie-driver-2.53.0.pom
artifact\:selenium-ie-driver\#jar\#jar\#-696524742.is-local=false
artifact.resolver=maven
artifact\:selenium-ie-driver\#pom.original\#pom\#956037920.is-local=false
resolver=maven
