##
## Poshi
##

    portal.url=http://192.168.118.10:8080/en/web/guest
    base.url=http://192.168.118.10:8080/en

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    output.dir.name=downloads

    test.name=ATLAboutUs,ATLHomePage,ATLPressRelease,ATLSearch,ATLTranslate

##
## Test This
##

    test.this.atlantia.portal.url=http://192.168.118.10:8080/en/web/guest
    test.this.atlantia.portal.login.admin.url=http://192.168.118.10:8080/en/web/guest/s6tu9mejqjmr2u2u
    test.this.atlantia.portal.admin.login=fabio.lanza@atlantia.com
    test.this.atlantia.portal.admin.password=password