##
## Account Properties
##
    www.admin.email.address=amos.fong@liferay.com.broken
    www.admin.password=test

##
## Component Names
##

    component.names=www

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Case
##

    test.case.available.property.names=\
        test.group,\
        testray.main.component.name,\
        type

##
## Testray
##

    testray.project.name=WWW

##
## Test Properties
##


    portal.url=http://localhost
	www.liferay.url=http://localhost