<<<<<<< HEAD
artifact.git.id=28fdf4dba0d1c5dd98df8325fac2a10b127822df
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/portal/com.liferay.portal.web/5.0.9/com.liferay.portal.web-5.0.9.war
=======
artifact.git.id=c6d274a1cf0e74b2baec9b7b7fe399144b283544
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/portal/com.liferay.portal.web/4.0.158/com.liferay.portal.web-4.0.158.war
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
