<<<<<<< HEAD
artifact.git.id=3afafaf0e32a85b734165313197da60aa2273623
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/portal/com.liferay.util.slf4j/6.0.0/com.liferay.util.slf4j-6.0.0.jar
=======
artifact.git.id=1e5b4c765b28dfee60eae5cd24bf8565bf330ce4
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/portal/com.liferay.util.slf4j/5.1.2/com.liferay.util.slf4j-5.1.2.jar
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
