<<<<<<< HEAD
artifact.git.id=1af6481c3b7effe97f7f18ffc9789ee5d9e1db7f
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/portal/com.liferay.util.taglib/6.0.0/com.liferay.util.taglib-6.0.0.jar
=======
artifact.git.id=7e74f3b4bcc3f9610c0aee73b233cb1193a3a70b
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/portal/com.liferay.util.taglib/5.3.5/com.liferay.util.taglib-5.3.5.jar
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
