#ivy cached data file for org.apache.httpcomponents#httpcomponents-core;4.4.3
#Fri Sep 16 11:26:36 PDT 2016
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-1520251610.is-local=false
artifact\:ivy\#ivy\#xml\#-1520251610.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-core/4.4.3/httpcomponents-core-4.4.3.pom
artifact\:httpcomponents-core\#pom.original\#pom\#-235465579.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-core/4.4.3/httpcomponents-core-4.4.3.pom
artifact\:httpcomponents-core\#pom.original\#pom\#-235465579.is-local=false
resolver=maven
