#ivy cached data file for org.seleniumhq.selenium#selenium-firefox-driver;2.53.0
#Fri Sep 16 11:55:13 PDT 2016
artifact.resolver=maven
artifact\:selenium-firefox-driver\#jar\#jar\#-1471653971.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-firefox-driver/2.53.0/selenium-firefox-driver-2.53.0.jar
artifact\:ivy\#ivy\#xml\#1912370607.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-firefox-driver/2.53.0/selenium-firefox-driver-2.53.0.pom
artifact\:ivy\#ivy\#xml\#1912370607.is-local=false
artifact\:selenium-firefox-driver\#pom.original\#pom\#180908691.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-firefox-driver/2.53.0/selenium-firefox-driver-2.53.0.pom
artifact\:selenium-firefox-driver\#jar\#jar\#-1471653971.is-local=false
artifact\:selenium-firefox-driver\#pom.original\#pom\#180908691.is-local=false
resolver=maven
