#ivy cached data file for org.seleniumhq.selenium#selenium-firefox-driver;2.47.1
#Wed Jun 22 11:43:53 PDT 2016
artifact\:selenium-firefox-driver\#jar\#jar\#-1633894309.is-local=false
artifact\:ivy\#ivy\#xml\#1750130269.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-firefox-driver/2.47.1/selenium-firefox-driver-2.47.1.pom
artifact\:ivy\#ivy\#xml\#1750130269.is-local=false
artifact.resolver=maven
resolver=maven
artifact\:selenium-firefox-driver\#jar\#jar\#-1633894309.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-firefox-driver/2.47.1/selenium-firefox-driver-2.47.1.jar
artifact\:selenium-firefox-driver\#pom.original\#pom\#18668353.is-local=false
artifact\:selenium-firefox-driver\#pom.original\#pom\#18668353.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-firefox-driver/2.47.1/selenium-firefox-driver-2.47.1.pom
