environmentBrowserName=Google Chrome 100
environmentOperatingSystemName=Ubuntu 22.04.1
projectDir=.
testrayBuildName=cifa.com - $(start.time)
testrayCasePriority=1
testrayComponentName=CIFA
testrayProductVersion=1.x
testrayProjectName=LXC
testrayRoutineName=MODL Daily
testrayTeamName=CIFA