<<<<<<< HEAD
artifact.git.id=fefa24e4f418336eded077c18db6104f5fdb8029
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/plugins/admin-theme/5.0.0/admin-theme-5.0.0.war
=======
artifact.git.id=35b93855adef014dd9f8b33c018339eed7056a0c
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/plugins/admin-theme/4.0.31/admin-theme-4.0.31.war
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
