#ivy cached data file for commons-codec#commons-codec;1.6
#Fri Sep 16 11:55:13 PDT 2016
artifact.resolver=maven
artifact\:commons-codec\#pom.original\#pom\#-1617744278.location=https\://plugins.gradle.org/m2/commons-codec/commons-codec/1.6/commons-codec-1.6.pom
resolver=maven
artifact\:commons-codec\#pom.original\#pom\#-1617744278.is-local=false
artifact\:ivy\#ivy\#xml\#-356992144.is-local=false
artifact\:ivy\#ivy\#xml\#-356992144.location=https\://plugins.gradle.org/m2/commons-codec/commons-codec/1.6/commons-codec-1.6.pom
