<<<<<<< HEAD
artifact.git.id=29659eb812a30183857c03bfb6104ccbc03d5e69
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/commerce/speedwell-theme/4.0.0/speedwell-theme-4.0.0.war
=======
artifact.git.id=d794fc5d0bb4af242d2ca1e711fa6e52e78bcaf0
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/commerce/speedwell-theme/3.0.19/speedwell-theme-3.0.19.war
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
