##
## Browser
##

    browser.type=chrome

##
## Component Names
##

    component.names=marketplace

##
## Marketplace Account Properties
##

    marketplace.admin.email.address=is-qa@liferay.com
    marketplace.admin.password=NAH@uth_xjr-chv2vhg

##
## Testray
##

    testray.project.name=Marketplace

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Case
##

    test.case.available.property.names=\
        test.group,\
        testray.main.component.name,\
        type

##
## Utilities
##

    test.base.dir.name=testFunctional
	test.include.dir.names=../shared
	output.dir.name=../tmp

##
## Test Properties
##

    portal.url=https://www-uat.liferay.com
	www.liferay.url=https://www-uat.liferay.com