##
## Poshi
##

    portal.url=http://localhost:8080

    save.screenshot=false

    test.base.dir.name=testFunctional/
    
    test.case.available.property.names=\
        testray.main.component.name

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.petrobras.portal.url=http://localhost:8080