#ivy cached data file for org.webbitserver#webbit;0.4.14
#Wed Jun 22 11:43:53 PDT 2016
artifact\:webbit\#pom.original\#pom\#2052334422.is-local=false
artifact\:webbit\#pom.original\#pom\#2052334422.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/webbitserver/webbit/0.4.14/webbit-0.4.14.pom
artifact\:ivy\#ivy\#xml\#-2102136748.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/webbitserver/webbit/0.4.14/webbit-0.4.14.pom
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-2102136748.is-local=false
artifact\:webbit\#jar\#jar\#399771760.is-local=false
artifact\:webbit\#jar\#jar\#399771760.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/webbitserver/webbit/0.4.14/webbit-0.4.14.jar
resolver=maven
