#ivy cached data file for org.apache.httpcomponents#httpmime;4.4.1
#Wed Jun 22 11:43:53 PDT 2016
artifact\:httpmime\#pom.original\#pom\#538847877.is-local=false
artifact\:httpmime\#pom.original\#pom\#538847877.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpmime/4.4.1/httpmime-4.4.1.pom
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-186635272.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpmime/4.4.1/httpmime-4.4.1.pom
artifact\:ivy\#ivy\#xml\#-186635272.is-local=false
artifact\:httpmime\#jar\#jar\#-1113714785.is-local=false
artifact\:httpmime\#jar\#jar\#-1113714785.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/httpmime/4.4.1/httpmime-4.4.1.jar
resolver=maven
