<<<<<<< HEAD
artifact.git.id=1dd7a4cd7b0b83bad8431a38ea538cc01fd83425
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/commerce/minium-theme/5.0.0/minium-theme-5.0.0.war
=======
artifact.git.id=cf5c04152fbfba58052bbcffe5695ab8d9f01454
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/commerce/minium-theme/4.0.20/minium-theme-4.0.20.war
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
