author=greg
change-log=
licenses=LGPL
<<<<<<< HEAD
liferay-versions=7.4.0+
=======
liferay-versions=7.3.0+
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
long-description=
module-group-id=liferay
module-incremental-version=1
name=test-portlet
page-url=http://www.liferay.com
short-description=
tags=