#ivy cached data file for org.seleniumhq.selenium#selenium-java;2.53.0
#Wed Oct 19 10:24:42 PDT 2016
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#30606731.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-java/2.53.0/selenium-java-2.53.0.pom
artifact\:selenium-java\#jar\#jar\#-708653857.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-java/2.53.0/selenium-java-2.53.0.jar
artifact\:selenium-java\#pom.original\#pom\#943908805.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-java/2.53.0/selenium-java-2.53.0.pom
artifact\:ivy\#ivy\#xml\#30606731.is-local=false
artifact\:selenium-java\#jar\#jar\#-708653857.is-local=false
artifact\:selenium-java\#pom.original\#pom\#943908805.is-local=false
resolver=maven
