##
## CI
##

    test.batch.property.query=testray.main.component.name == 'CGE'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'CGE')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'CGE')

##
## Poshi
##

    portal.url=https://customer:QqOXs2UMbRulfOAD8dhAsSulClZk33@webserver-portalescge-uat.lfr.cloud

    save.screenshot=false

    test.base.dir.name=testFunctional/
    
    test.case.available.property.names=\
        test.env,\
        testray.main.component.name

    test.name=<list-of-test-case-files-tbd>

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.cge.portal.url.uat=https://webserver-portalescge-uat.lfr.cloud
    test.this.cge.portal.url.prod=http://<project-prod-url-tbd>

    test.this.cge.test.account.uat.admin.login=lfrgs.cge@gmail.com
    test.this.cge.test.account.uat.admin.password=qaliferaycge
    
    test.this.cge.test.account.uat.user.login=<uat-user-login-tbd>
    test.this.cge.test.account.uat.user.password=<uat-user-password-tbd>

    test.this.cge.test.account.webserver.user.login=customer
    test.this.cge.test.account.webserver.user.password=QqOXs2UMbRulfOAD8dhAsSulClZk33

##
## Testray
##

    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.project.name=LXC

    testray.routine.name[uat]=MODL Daily