##
## Component Names
##

    component.names=support-qa

##
## Account Properties
##
    support.admin.email.address=amos.fong@liferay.com.broken
    support.admin.password=supportforlife

    web.admin.email.address=amos.fong@liferay.com.broken
    web.admin.password=test

    zendesk.admin.email.address=zendesk.admin@liferay.com.broken
    zendesk.admin.password=zendeskqauser

    zendesk.api.token=H5vC4cxSZdgZdKYVTDNPdmTKXqVUeQAmUWxVfIC4

##
## Testray
##

    testray.project.name=Zendesk

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Case
##

    test.case.available.property.names=type,testray.main.component.name

##
## Utilities
##

    test.base.dir.name=testFunctional
    test.include.dir.names=../shared

##
## Test Properties
##

    osb.admin.popup.title=OSB Admin - Control Panel

	osb.to.zendesk.sync.poll.interval.in.seconds=10
	osb.to.zendesk.sync.poll.maximum.iterations=15

	portal.url=https://liferaysupport1528999723.zendesk.com

    support.liferay.url=https://customer-uat.liferay.com
    support.liferay.web.id=liferay.com

    web.liferay.url=https://web-uat.liferay.com
    web.liferay.web.id=liferay.com

	zendesk.liferay.url=https://liferaysupport1528999723.zendesk.com