#ivy cached data file for org.bytedeco#javacpp;0.9
#Thu Sep 21 18:55:39 PDT 2017
artifact\:ivy\#ivy\#xml\#733092838.is-local=false
artifact.resolver=maven
artifact\:javacpp\#maven-plugin\#jar\#1319259220.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/bytedeco/javacpp/0.9/javacpp-0.9.jar
artifact\:javacpp\#maven-plugin\#jar\#1319259220.is-local=false
resolver=maven
artifact\:javacpp\#pom.original\#pom\#1927171248.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/bytedeco/javacpp/0.9/javacpp-0.9.pom
artifact\:javacpp\#pom.original\#pom\#1927171248.is-local=false
artifact\:ivy\#ivy\#xml\#733092838.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/bytedeco/javacpp/0.9/javacpp-0.9.pom
