#ivy cached data file for org.bytedeco#javacpp;0.10
#Wed Oct 19 10:24:42 PDT 2016
artifact\:javacpp\#maven-plugin\#jar\#1659421518.is-local=false
artifact\:javacpp\#maven-plugin\#jar\#1659421518.location=https\://plugins.gradle.org/m2/org/bytedeco/javacpp/0.10/javacpp-0.10.jar
artifact.resolver=maven
artifact\:javacpp\#pom.original\#pom\#-2027633750.is-local=false
artifact\:javacpp\#pom.original\#pom\#-2027633750.location=https\://plugins.gradle.org/m2/org/bytedeco/javacpp/0.10/javacpp-0.10.pom
resolver=maven
artifact\:ivy\#ivy\#xml\#1073255136.location=https\://plugins.gradle.org/m2/org/bytedeco/javacpp/0.10/javacpp-0.10.pom
artifact\:ivy\#ivy\#xml\#1073255136.is-local=false
