#ivy cached data file for net.sourceforge.nekohtml#nekohtml;1.9.22
#Wed Jun 22 11:43:53 PDT 2016
artifact.resolver=maven
artifact\:nekohtml\#jar\#jar\#-1009399768.is-local=false
artifact\:nekohtml\#jar\#jar\#-1009399768.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/sourceforge/nekohtml/nekohtml/1.9.22/nekohtml-1.9.22.jar
resolver=maven
artifact\:ivy\#ivy\#xml\#-1347339705.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/sourceforge/nekohtml/nekohtml/1.9.22/nekohtml-1.9.22.pom
artifact\:ivy\#ivy\#xml\#-1347339705.is-local=false
artifact\:nekohtml\#pom.original\#pom\#643162894.is-local=false
artifact\:nekohtml\#pom.original\#pom\#643162894.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/sourceforge/nekohtml/nekohtml/1.9.22/nekohtml-1.9.22.pom
