#ivy cached data file for org.apache#apache;7
#Wed Jun 22 11:43:34 PDT 2016
artifact\:ivy\#ivy\#xml\#-1735449594.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/apache/7/apache-7.pom
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-1735449594.is-local=false
artifact\:apache\#pom.original\#pom\#142580565.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/apache/7/apache-7.pom
artifact\:apache\#pom.original\#pom\#142580565.is-local=false
resolver=maven
