#ivy cached data file for org.apache#apache;16
#Wed Jun 22 11:43:03 PDT 2016
artifact.resolver=maven
artifact\:apache\#pom.original\#pom\#152072619.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/apache/16/apache-16.pom
artifact\:apache\#pom.original\#pom\#152072619.is-local=false
artifact\:ivy\#ivy\#xml\#-1725957540.is-local=false
artifact\:ivy\#ivy\#xml\#-1725957540.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/apache/16/apache-16.pom
resolver=maven
