#ivy cached data file for io.netty#netty;3.5.2.Final
#Wed Jun 22 11:43:53 PDT 2016
artifact\:ivy\#ivy\#xml\#-1911719435.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/io/netty/netty/3.5.2.Final/netty-3.5.2.Final.pom
artifact\:ivy\#ivy\#xml\#-1911719435.is-local=false
artifact.resolver=maven
artifact\:netty\#pom.original\#pom\#1213923256.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/io/netty/netty/3.5.2.Final/netty-3.5.2.Final.pom
artifact\:netty\#bundle\#jar\#-1412157023.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/io/netty/netty/3.5.2.Final/netty-3.5.2.Final.jar
resolver=maven
artifact\:netty\#pom.original\#pom\#1213923256.is-local=false
artifact\:netty\#bundle\#jar\#-1412157023.is-local=false
