#ivy cached data file for org.seleniumhq.selenium#selenium-api;2.47.1
#Wed Jun 22 11:43:53 PDT 2016
artifact\:selenium-api\#pom.original\#pom\#532108545.is-local=false
artifact\:selenium-api\#pom.original\#pom\#532108545.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-api/2.47.1/selenium-api-2.47.1.pom
artifact\:selenium-api\#jar\#jar\#-1120454117.is-local=false
artifact\:selenium-api\#jar\#jar\#-1120454117.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-api/2.47.1/selenium-api-2.47.1.jar
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-669998371.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-api/2.47.1/selenium-api-2.47.1.pom
artifact\:ivy\#ivy\#xml\#-669998371.is-local=false
resolver=maven
