##
## Browser
##
    browser.type=chrome

##
## Account Properties
##
    mirror.user=er-hu@liferay.com
    mirror.password=n3tr1sk

##
## Component Names
##

    component.names=patcher-builder

##
## Test Case
##

    test.case.available.property.names=\
        priority,\
        testray.main.component.name

##
## Test Batch
##

    test.batch.property.query=true
    test.batch.property.query[websites-patcher-builder-daily]=\
        (priority == "5" OR priority == "4")
    test.batch.property.query[websites-patcher-builder-weekly]=\
        (priority == "3" OR priority == "2")

##
## Testray
##

    testray.project.name=Patcher

##
## Test properties
##

    job.completion.poll.interval.in.minutes=6
    job.completion.poll.maximum.iterations=15

    portal.url=http://cloud-10-50-0-133.liferay.com/