##
## Component Names
##

    component.names=patcher-builder

##
## Test Batch
##

    test.batch.property.query=true

##
## Testray
##

    testray.project.name=Patcher

##
## Test properties
##

    job.completion.poll.interval.in.minutes=6
    job.completion.poll.maximum.iterations=15

    portal.url=http://cloud-10-50-0-133.liferay.com/