#ivy cached data file for org.apache.commons#commons-parent;9
#Wed Jun 22 11:43:02 PDT 2016
artifact\:commons-parent\#pom.original\#pom\#2012830134.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/9/commons-parent-9.pom
artifact\:commons-parent\#pom.original\#pom\#2012830134.is-local=false
artifact\:ivy\#ivy\#xml\#2023594798.is-local=false
artifact\:ivy\#ivy\#xml\#2023594798.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/9/commons-parent-9.pom
artifact.resolver=maven
resolver=maven
