#ivy cached data file for org.apache.commons#commons-parent;17
#Wed Jun 22 11:43:36 PDT 2016
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#2033080599.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/17/commons-parent-17.pom
artifact\:commons-parent\#pom.original\#pom\#2022315935.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/17/commons-parent-17.pom
artifact\:ivy\#ivy\#xml\#2033080599.is-local=false
resolver=maven
artifact\:commons-parent\#pom.original\#pom\#2022315935.is-local=false
