#ivy cached data file for org.apache.commons#commons-parent;28
#Fri Sep 16 11:25:55 PDT 2016
artifact\:commons-parent\#pom.original\#pom\#2022516031.is-local=false
artifact\:ivy\#ivy\#xml\#2033280695.is-local=false
artifact.resolver=maven
resolver=maven
artifact\:commons-parent\#pom.original\#pom\#2022516031.location=https\://plugins.gradle.org/m2/org/apache/commons/commons-parent/28/commons-parent-28.pom
artifact\:ivy\#ivy\#xml\#2033280695.location=https\://plugins.gradle.org/m2/org/apache/commons/commons-parent/28/commons-parent-28.pom
