#ivy cached data file for org.apache.commons#commons-parent;14
#Wed Jun 22 11:43:39 PDT 2016
artifact\:ivy\#ivy\#xml\#2033061840.is-local=false
artifact\:ivy\#ivy\#xml\#2033061840.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/14/commons-parent-14.pom
artifact.resolver=maven
artifact\:commons-parent\#pom.original\#pom\#2022297176.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/14/commons-parent-14.pom
artifact\:commons-parent\#pom.original\#pom\#2022297176.is-local=false
resolver=maven
