#ivy cached data file for org.apache.commons#commons-parent;34
#Wed Jun 22 11:42:50 PDT 2016
artifact\:commons-parent\#pom.original\#pom\#2022684862.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/34/commons-parent-34.pom
artifact\:commons-parent\#pom.original\#pom\#2022684862.is-local=false
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#2033449526.is-local=false
artifact\:ivy\#ivy\#xml\#2033449526.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/34/commons-parent-34.pom
resolver=maven
