#ivy cached data file for org.apache.commons#commons-parent;22
#Fri Sep 16 11:26:02 PDT 2016
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#2033243177.is-local=false
artifact\:ivy\#ivy\#xml\#2033243177.location=https\://plugins.gradle.org/m2/org/apache/commons/commons-parent/22/commons-parent-22.pom
artifact\:commons-parent\#pom.original\#pom\#2022478513.location=https\://plugins.gradle.org/m2/org/apache/commons/commons-parent/22/commons-parent-22.pom
artifact\:commons-parent\#pom.original\#pom\#2022478513.is-local=false
resolver=maven
