#ivy cached data file for org.apache.commons#commons-parent;36
#Wed Jun 22 11:43:38 PDT 2016
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#2033462032.is-local=false
artifact\:ivy\#ivy\#xml\#2033462032.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/36/commons-parent-36.pom
artifact\:commons-parent\#pom.original\#pom\#2022697368.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/36/commons-parent-36.pom
artifact\:commons-parent\#pom.original\#pom\#2022697368.is-local=false
resolver=maven
