#ivy cached data file for org.apache.commons#commons-parent;32
#Thu Sep 21 18:55:19 PDT 2017
artifact\:commons-parent\#pom.original\#pom\#2022672356.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/32/commons-parent-32.pom
artifact\:ivy\#ivy\#xml\#2033437020.is-local=false
artifact\:ivy\#ivy\#xml\#2033437020.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/commons/commons-parent/32/commons-parent-32.pom
artifact\:commons-parent\#pom.original\#pom\#2022672356.is-local=false
artifact.resolver=maven
resolver=maven
