#ivy cached data file for org.seleniumhq.selenium#selenium-remote-driver;2.47.1
#Wed Jun 22 11:43:53 PDT 2016
artifact\:selenium-remote-driver\#jar\#jar\#692482186.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-remote-driver/2.47.1/selenium-remote-driver-2.47.1.jar
artifact\:ivy\#ivy\#xml\#-1109104161.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-remote-driver/2.47.1/selenium-remote-driver-2.47.1.pom
artifact\:ivy\#ivy\#xml\#-1109104161.is-local=false
artifact\:selenium-remote-driver\#jar\#jar\#692482186.is-local=false
artifact.resolver=maven
artifact\:selenium-remote-driver\#pom.original\#pom\#-1949922448.is-local=false
artifact\:selenium-remote-driver\#pom.original\#pom\#-1949922448.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/seleniumhq/selenium/selenium-remote-driver/2.47.1/selenium-remote-driver-2.47.1.pom
resolver=maven
