#ivy cached data file for org.seleniumhq.selenium#selenium-remote-driver;2.53.0
#Wed Oct 19 10:24:42 PDT 2016
artifact\:selenium-remote-driver\#pom.original\#pom\#-1787682110.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-remote-driver/2.53.0/selenium-remote-driver-2.53.0.pom
artifact.resolver=maven
artifact\:selenium-remote-driver\#jar\#jar\#854722524.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-remote-driver/2.53.0/selenium-remote-driver-2.53.0.jar
artifact\:selenium-remote-driver\#pom.original\#pom\#-1787682110.is-local=false
artifact\:selenium-remote-driver\#jar\#jar\#854722524.is-local=false
artifact\:ivy\#ivy\#xml\#-946863823.location=https\://plugins.gradle.org/m2/org/seleniumhq/selenium/selenium-remote-driver/2.53.0/selenium-remote-driver-2.53.0.pom
artifact\:ivy\#ivy\#xml\#-946863823.is-local=false
resolver=maven
