#ivy cached data file for net.minidev#accessors-smart;1.1
#Fri Sep 16 11:55:13 PDT 2016
artifact\:ivy\#ivy\#xml\#-1837233795.is-local=false
artifact\:accessors-smart\#bundle\#jar\#580008223.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/minidev/accessors-smart/1.1/accessors-smart-1.1.jar
artifact\:accessors-smart\#pom.original\#pom\#-1088878794.is-local=false
artifact\:accessors-smart\#pom.original\#pom\#-1088878794.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/minidev/accessors-smart/1.1/accessors-smart-1.1.pom
artifact.resolver=maven
artifact\:accessors-smart\#bundle\#jar\#580008223.is-local=false
artifact\:ivy\#ivy\#xml\#-1837233795.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/minidev/accessors-smart/1.1/accessors-smart-1.1.pom
resolver=maven
