##
## Component Names
##

    component.names=liferay-dev

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Liferay Dev'

##
## Test Case
##

    test.case.available.property.names=\
        test.group,\
        testray.main.component.name,\
        type

##
## Test This
##

    test.this.portal.url=http://uat.liferay.dev

    test.this.liferaydev.admin=liferaydev-user-uat@liferay.com
    test.thisliferaydev.admin.password=awPCGTw8_wWtMzYWwy@8

    test.this.liferaydev.user=liferaydev-admin-uat@liferay.com
    test.this.liferaydev.user.password=CsATHcNA!JXURVRov8VT

    test.this.webserver.user=liferaydev-test-uat
    test.this.webserver.user.password=suLEcMpHzYAqxXzWRRZEDkqe

##
## Testray
##

    testray.project.name=liferay-dev