##
## Component Names
##

    component.names=liferay-dev

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Liferay Dev'

##
## Test Case
##

    test.case.available.property.names=\
        test.group,\
        testray.main.component.name,\
        type

##
## Testray
##

    testray.project.name=liferay-dev

##
## Test Properties
##

    portal.url=http://uat.liferay.dev

##
## Test Accounts 
##

    test.liferaydev.admin=liferaydev-user-uat@liferay.com
    test.liferaydev.admin.password=awPCGTw8_wWtMzYWwy@8

    test.liferaydev.user=liferaydev-admin-uat@liferay.com
    test.liferaydev.user.password=CsATHcNA!JXURVRov8VT

    test.webserver.user=liferaydev-test-uat
    test.webserver.user.password=suLEcMpHzYAqxXzWRRZEDkqe