testrayUserName=[liferay_user_name]@liferay.com
testrayUserPassword=[liferay_user_password]

environmentBrowserName=Google Chrome 86
environmentOperatingSystemName=Cent OS 7

projectDir=.

testrayBuildName=Liferay Dev Build - $(start.time)
testrayCasePriority=1
testrayComponentName=Liferay Dev
testrayProductVersion=1.x
testrayProjectName=LXC: Liferay Dev
testrayRoutineName=Liferay Dev
testrayServerURL=https://testray.liferay.com
testrayTeamName=Liferay Dev