#ivy cached data file for org.slf4j#slf4j-parent;1.7.13
#Wed Jun 22 11:43:22 PDT 2016
artifact\:slf4j-parent\#pom.original\#pom\#-617435988.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/slf4j/slf4j-parent/1.7.13/slf4j-parent-1.7.13.pom
artifact\:ivy\#ivy\#xml\#811116423.is-local=false
artifact\:slf4j-parent\#pom.original\#pom\#-617435988.is-local=false
artifact.resolver=maven
resolver=maven
artifact\:ivy\#ivy\#xml\#811116423.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/slf4j/slf4j-parent/1.7.13/slf4j-parent-1.7.13.pom
