##
## Component Names
##

    component.names=marketplace

##
## Marketplace Account Properties
##

  	marketplace.email.address.1=liferay.qa.marketplace@gmail.com.broken
  	marketplace.email.address.2=liferay.qa.marketplace.1@gmail.com.broken
  	marketplace.email.address.3=lrqa.merchant.1@liferay.com
  	marketplace.email.address.4=lrqa.personal.2@liferay.com
  	marketplace.email.address.5=liferay.qa.admin@liferay.com
  	marketplace.email.password.1=test
  	marketplace.email.password.2=test
  	marketplace.email.password.3=Liferay123
  	marketplace.email.password.4=Liferay123
  	marketplace.email.password.5=liferayqa

##
## Test Batch
##

    test.batch.property.names=testray.main.component.name,testray.main.component.name,testray.main.component.name
    test.batch.property.values=Marketplace,MarketplaceRegistration,MarketplaceCompany

##
## Utilities
##

    portal.url=http://www-nightly.liferay.com
    portal.marketplace.url=http://www-nightly.liferay.com/marketplace
    portal.login.url=http://www-nightly.liferay.com/sign-in
    portal.logout.url=http://www-nightly.liferay.com/c/portal/logout
