##
## Component Names
##

    component.names=lrdcom

##
## LRDCOM Account Properties
##

    lrdcom.email.address.1=liferay.qa@gmail.com.broken
    lrdcom.email.address.2=liferay.qa2@gmail.com
    lrdcom.email.address.3=liferay.qa3@gmail.com.broken
    lrdcom.email.address.4=liferay.qa4@gmail.com.broken
    lrdcom.email.address.5=liferay.qa.admin@liferay.com

    lrdcom.email.password.1=test
    lrdcom.email.password.2=testtest
    lrdcom.email.password.3=test
    lrdcom.email.password.4=test
    lrdcom.email.password.5=liferayqa

##
## Testray
##

    testray.project.name=LRDCOM

##
## Test Batch
##

    test.batch.property.names=testray.main.component.name,testray.main.component.name
    test.batch.property.values=lrdcom-web,lrdcom-www

##
## Utilities
##

    test.base.dir.name=testFunctional
    test.include.dir.names=\
      ../marketplace/testFunctional,\
      ../osb/testFunctional,\
      ../shared

##
## Test Properties
##

    lrdcom.login.url=https://www-uat.liferay.com/c/portal/login?p_l_id=231354466
    lrdcom.logout.url=https://www-uat.liferay.com/c/portal/logout
    lrdcom.www.url=https://www-uat.liferay.com