#ivy cached data file for com.deque#axe-selenium;1.1
#Wed Oct 19 10:24:42 PDT 2016
artifact\:axe-selenium\#jar\#jar\#18204651.is-local=false
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#634423403.location=https\://plugins.gradle.org/m2/com/deque/axe-selenium/1.1/axe-selenium-1.1.pom
artifact\:ivy\#ivy\#xml\#634423403.is-local=false
artifact\:axe-selenium\#pom.original\#pom\#1670767313.location=https\://plugins.gradle.org/m2/com/deque/axe-selenium/1.1/axe-selenium-1.1.pom
artifact\:axe-selenium\#pom.original\#pom\#1670767313.is-local=false
resolver=maven
artifact\:axe-selenium\#jar\#jar\#18204651.location=https\://plugins.gradle.org/m2/com/deque/axe-selenium/1.1/axe-selenium-1.1.jar
