<<<<<<< HEAD
artifact.git.id=bbede231f5ed8d8984ac5152c1483f1d6329b761
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/plugins/saml-hook/7.4.10.1/saml-hook-7.4.10.1.war
=======
artifact.git.id=d553927a0b3e74e3be47184f07db51e07766a622
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/plugins/saml-hook/7.3.10.18/saml-hook-7.3.10.18.war
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
