<<<<<<< HEAD
artifact.git.id=30afb0a51d86f0eece99c2019e74f9eed9cc1e31
artifact.sources-commercial.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.notifications.uad/6.0.0/com.liferay.notifications.uad-6.0.0-sources-commercial.jar
artifact.sources.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.notifications.uad/6.0.0/com.liferay.notifications.uad-6.0.0-sources.jar
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.notifications.uad/6.0.0/com.liferay.notifications.uad-6.0.0.jar
=======
artifact.git.id=e7a45bb41ebd5b7fe7b3b8a56f14c40ebe9c2407
artifact.sources-commercial.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.notifications.uad/5.0.13/com.liferay.notifications.uad-5.0.13-sources-commercial.jar
artifact.sources.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.notifications.uad/5.0.13/com.liferay.notifications.uad-5.0.13-sources.jar
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.notifications.uad/5.0.13/com.liferay.notifications.uad-5.0.13.jar
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
