#ivy cached data file for org.apache.httpcomponents#project;7
#Wed Jun 22 11:42:47 PDT 2016
artifact\:ivy\#ivy\#xml\#-1106913924.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/project/7/project-7.pom
artifact\:project\#pom.original\#pom\#-2136795298.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/org/apache/httpcomponents/project/7/project-7.pom
artifact\:project\#pom.original\#pom\#-2136795298.is-local=false
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-1106913924.is-local=false
resolver=maven
