#ivy cached data file for com.google.code.gson#gson;2.2.4
#Wed Oct 19 10:24:42 PDT 2016
artifact\:gson\#pom.original\#pom\#1126560213.is-local=false
artifact\:gson\#pom.original\#pom\#1126560213.location=https\://plugins.gradle.org/m2/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-445033455.location=https\://plugins.gradle.org/m2/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom
artifact\:ivy\#ivy\#xml\#-445033455.is-local=false
resolver=maven
