app.marketplace.id=74878779
app.marketplace.title=Liferay CE Static
<<<<<<< HEAD
app.marketplace.version=9.0.0
app.portal.build=7400
=======
app.marketplace.version=8.0.0
app.portal.build=7306
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
