#ivy cached data file for com.jayway.jsonpath#json-path;2.1.0
#Wed Oct 19 10:24:42 PDT 2016
artifact\:json-path\#jar\#jar\#-81125691.is-local=false
artifact\:json-path\#pom.original\#pom\#1571436971.is-local=false
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-488362976.is-local=false
artifact\:ivy\#ivy\#xml\#-488362976.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/jayway/jsonpath/json-path/2.1.0/json-path-2.1.0.pom
artifact\:json-path\#jar\#jar\#-81125691.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/jayway/jsonpath/json-path/2.1.0/json-path-2.1.0.jar
resolver=maven
artifact\:json-path\#pom.original\#pom\#1571436971.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/jayway/jsonpath/json-path/2.1.0/json-path-2.1.0.pom
