#ivy cached data file for junit#junit;4.12
#Thu Jan 05 15:28:37 PST 2017
artifact\:junit\#pom.original\#pom\#440145813.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/junit/junit/4.12/junit-4.12.pom
artifact\:junit\#pom.original\#pom\#440145813.is-local=false
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#1727529382.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/junit/junit/4.12/junit-4.12.pom
artifact\:ivy\#ivy\#xml\#1727529382.is-local=false
artifact\:junit\#jar\#jar\#-1212416849.is-local=false
artifact\:junit\#jar\#jar\#-1212416849.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/junit/junit/4.12/junit-4.12.jar
resolver=maven
