<<<<<<< HEAD
artifact.git.id=abd22d11696ee1797c963cc34c8f3d53b432581a
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/plugins/opensocial-portlet/7.4.10.2/opensocial-portlet-7.4.10.2.war
=======
artifact.git.id=359ef7bcd3751ebfff2c469029db14673e8ac816
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/plugins/opensocial-portlet/7.3.10.27/opensocial-portlet-7.3.10.27.war
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
