#ivy cached data file for org.codehaus.groovy#groovy;2.4.5
#Fri Sep 16 11:55:13 PDT 2016
artifact\:groovy\#jar\#jar\#273134435.is-local=false
artifact\:groovy\#pom.original\#pom\#1925697097.is-local=false
artifact\:groovy\#pom.original\#pom\#1925697097.location=https\://plugins.gradle.org/m2/org/codehaus/groovy/groovy/2.4.5/groovy-2.4.5.pom
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-2004961734.location=https\://plugins.gradle.org/m2/org/codehaus/groovy/groovy/2.4.5/groovy-2.4.5.pom
artifact\:ivy\#ivy\#xml\#-2004961734.is-local=false
resolver=maven
artifact\:groovy\#jar\#jar\#273134435.location=https\://plugins.gradle.org/m2/org/codehaus/groovy/groovy/2.4.5/groovy-2.4.5.jar
