#ivy cached data file for org.apache.httpcomponents#httpclient;4.5.1
#Wed Oct 19 10:24:42 PDT 2016
artifact\:ivy\#ivy\#xml\#1873384027.is-local=false
artifact\:ivy\#ivy\#xml\#1873384027.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.pom
artifact\:httpclient\#jar\#jar\#-2000493951.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar
artifact\:httpclient\#pom.original\#pom\#-347931289.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.pom
artifact\:httpclient\#jar\#jar\#-2000493951.is-local=false
artifact.resolver=maven
artifact\:httpclient\#pom.original\#pom\#-347931289.is-local=false
resolver=maven
