#ivy cached data file for org.apache.httpcomponents#httpclient;4.3.3
#Fri Sep 16 11:55:13 PDT 2016
artifact\:ivy\#ivy\#xml\#1861378267.is-local=false
artifact.resolver=maven
artifact\:httpclient\#pom.original\#pom\#-359937049.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.pom
artifact\:httpclient\#pom.original\#pom\#-359937049.is-local=false
resolver=maven
artifact\:ivy\#ivy\#xml\#1861378267.location=https\://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.pom
