app.marketplace.id=106191336
app.marketplace.title=Liferay CE User Groups Admin
<<<<<<< HEAD
app.marketplace.version=4.0.1
app.portal.build=7400
=======
app.marketplace.version=3.0.5
app.portal.build=7306
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
