##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Cosette'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Cosette')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Cosette')

##
## Poshi
##

    output.dir.name=downloads

    portal.url=https://cosette-modl:hdf45HcLlvqSxv51FnxMM8W3@azor-modl.lxc.liferay.com

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=Coupon,HomePageElements,HomePageNavigation

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.cosette.azor.portal.url.uat=https://azor-modl.lxc.liferay.com
    test.this.cosette.benicar.portal.url.uat=https://benicar-modl.lxc.liferay.com
    test.this.cosette.tribenzor.portal.url.uat=https://tribenzor-modl.lxc.liferay.com
    test.this.cosette.welchol.portal.url.uat=https://welchol-modl.lxc.liferay.com
    test.this.cosette.welcholhcp.portal.url.uat=https://welcholhcp-modl.lxc.liferay.com

    test.this.cosette.portal.url.prod=http://<project-prod-url-tbd>

    test.this.cosette.test.account.uat.admin.login=<uat-admin-login-tbd>
    test.this.cosette.test.account.uat.admin.password=<uat-admin-password-tbd>

    test.this.cosette.test.account.uat.user.login=<uat-user-login-tbd>
    test.this.cosette.test.account.uat.user.password=<uat-user-password-tbd>

    test.this.cosette.test.account.webserver.user.login=cosette-modl
    test.this.cosette.test.account.webserver.user.password=hdf45HcLlvqSxv51FnxMM8W3

##
## Testray
##

    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.project.name=LXC

    testray.routine.name[uat]=MODL Daily