#ivy cached data file for com.liferay#com.liferay.gradle.util;1.0.23
#Wed Oct 19 10:24:04 PDT 2016
artifact\:com.liferay.gradle.util\#jar\#jar\#781371964.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.gradle.util/1.0.23/com.liferay.gradle.util-1.0.23.jar
artifact\:ivy\#ivy\#xml\#143230773.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.gradle.util/1.0.23/com.liferay.gradle.util-1.0.23.pom
artifact\:ivy\#ivy\#xml\#143230773.is-local=false
artifact\:com.liferay.gradle.util\#pom.original\#pom\#-1861032670.is-local=false
artifact\:com.liferay.gradle.util\#pom.original\#pom\#-1861032670.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.gradle.util/1.0.23/com.liferay.gradle.util-1.0.23.pom
artifact\:com.liferay.gradle.util\#jar\#jar\#781371964.is-local=false
artifact.resolver=maven
resolver=maven
