#ivy cached data file for net.minidev#json-smart;2.2
#Fri Sep 16 11:55:13 PDT 2016
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-325887761.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/minidev/json-smart/2.2/json-smart-2.2.pom
artifact\:ivy\#ivy\#xml\#-325887761.is-local=false
artifact\:json-smart\#pom.original\#pom\#1021015844.is-local=false
artifact\:json-smart\#pom.original\#pom\#1021015844.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/minidev/json-smart/2.2/json-smart-2.2.pom
artifact\:json-smart\#bundle\#jar\#-1605064435.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/net/minidev/json-smart/2.2/json-smart-2.2.jar
resolver=maven
artifact\:json-smart\#bundle\#jar\#-1605064435.is-local=false
