#ivy cached data file for com.liferay#net.jsourcerer.webdriver.JSErrorCollector;0.6
#Fri Sep 16 11:55:13 PDT 2016
artifact.resolver=maven
artifact\:ivy\#ivy\#xml\#-1225128393.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/net.jsourcerer.webdriver.JSErrorCollector/0.6/net.jsourcerer.webdriver.JSErrorCollector-0.6.pom
artifact\:ivy\#ivy\#xml\#-1225128393.is-local=false
artifact\:net.jsourcerer.webdriver.JSErrorCollector\#jar\#jar\#359856429.is-local=false
artifact\:net.jsourcerer.webdriver.JSErrorCollector\#jar\#jar\#359856429.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/net.jsourcerer.webdriver.JSErrorCollector/0.6/net.jsourcerer.webdriver.JSErrorCollector-0.6.jar
artifact\:net.jsourcerer.webdriver.JSErrorCollector\#pom.original\#pom\#2012419091.location=https\://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/liferay/net.jsourcerer.webdriver.JSErrorCollector/0.6/net.jsourcerer.webdriver.JSErrorCollector-0.6.pom
artifact\:net.jsourcerer.webdriver.JSErrorCollector\#pom.original\#pom\#2012419091.is-local=false
resolver=maven
