##
## Component Names
##

    component.names=salesforce


##
## Salesforce Account Properties
##

	salesforce.email.address=is-sales-qa@liferay.com.qa

	salesforce.email.password=l1f3ray151

##
## Utilities
##

	portal.url=https://test.salesforce.com/