##
## Component Names
##

    component.names=support-qa

##
## Utilities
##

#portal.url=https://dossiera-uat.liferay.com/

salesforce.url=https://test.salesforce.com/
salesforce.email.address.1=is-sales-qa@liferay.com.qa
salesforce.email.password.1=l1f3ray151
salesforce.email.address.2=is-sales-qa@liferay.com.sales
salesforce.email.password.2=l1f3ray151