##
## Component Names
##

    component.names=salesforce-acceptance


##
## Salesforce Account Properties
##

	salesforce.email.address.1=is-sales-qa@liferay.com.qa
	salesforce.email.address.2=is-sales-qa@liferay.com.sales

	salesforce.email.password.1=l1f3ray151
	salesforce.email.password.2=l1f3ray151

##
## Utilities
##

	portal.url=https://test.salesforce.com/