buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "latest.release"
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.poshi.runner", version: "3.0.60"
	}

	repositories {
		mavenLocal()n
		maven {
		turl file("/opt/dev/projects/github/liferay-qa-websites-ee/.git/.m2-tmp")
		}

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.poshi.defaults"

dependencies {
	poshiRunnerResources group: "com.liferay", name: "com.liferay.poshi.runner.resources", version: "1.0.14"
	poshiRunnerResources group: "com.liferay.poshi.runner.resources", name: "portal-7.3.x", version: "20221115-b92b907"
}