##
## Component Names
##

    component.names=patcher-builder

##
## Test Batch
##

    test.batch.property.query=true

##
## Testray
##

    testray.project.name=Patcher

##
## Utilities
##

    portal.url=https://cloud-10-50-0-226.liferay.com/