##
## Component Names
##

    component.names=patcher-builder

##
## Testray
##

    testray.project.name=Patcher Builder

##
## Utilities
##

    test.base.dir.name=testFunctional

##
## Utilities
##

    portal.url=http://cloud-10-50-0-226

##
## Test Properties
##

    jenkins.authentication.token=raen3Aib