app.marketplace.id=
app.marketplace.title=Liferay CE Data Cleanup
<<<<<<< HEAD
app.marketplace.version=2.0.1
app.portal.build=7400
=======
app.marketplace.version=1.0.1
app.portal.build=7306
>>>>>>> 3cc350081830d5b3ed7848d769d3985a6bbf0469
